include "login.fbs";
include "player.fbs";
include "movement.fbs";
include "attack.fbs";
include "item.fbs";
include "interact.fbs";
include "inventory.fbs";

namespace ProtoType.Net;

union Payload {
  C2S_Login,
  S2C_LoginFail,
  S2C_LoginSuccess,
  S2C_SendAvatarInfo,
  S2C_SendPlayerInfo,
  S2C_PlayerLeft,
  C2S_MoveInput,
  S2C_MoveState,
  C2S_AttackRequest,
  S2C_AttackResult,
  S2C_AttackBroadcast,
  C2S_ItemUseRequest,
  S2C_ItemUseResult,
  S2C_ItemUseBroadcast,
  C2S_InteractRequest,
  S2C_InteractResult,
  C2S_SaveInventory,
}

table Packet {
  payload: Payload;
}

root_type Packet;
file_identifier "PTPK";
