// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INVENTORY_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_INVENTORY_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ProtoType {
namespace Net {

struct InventoryItemEntry;
struct InventoryItemEntryBuilder;
struct InventoryItemEntryT;

struct C2S_SaveInventory;
struct C2S_SaveInventoryBuilder;
struct C2S_SaveInventoryT;

struct EquipmentItemEntry;
struct EquipmentItemEntryBuilder;
struct EquipmentItemEntryT;

struct C2S_SaveEquipment;
struct C2S_SaveEquipmentBuilder;
struct C2S_SaveEquipmentT;

struct QuickSlotItemEntry;
struct QuickSlotItemEntryBuilder;
struct QuickSlotItemEntryT;

struct C2S_SaveQuickSlots;
struct C2S_SaveQuickSlotsBuilder;
struct C2S_SaveQuickSlotsT;

struct C2S_RequestStash;
struct C2S_RequestStashBuilder;
struct C2S_RequestStashT;

struct S2C_StashState;
struct S2C_StashStateBuilder;
struct S2C_StashStateT;

struct C2S_SaveStash;
struct C2S_SaveStashBuilder;
struct C2S_SaveStashT;

struct InventoryItemEntryT : public ::flatbuffers::NativeTable {
  typedef InventoryItemEntry TableType;
  std::string item_id{};
  int16_t grid_x = 0;
  int16_t grid_y = 0;
  bool rotated = false;
  int16_t stack_count = 1;
};

struct InventoryItemEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InventoryItemEntryT NativeTableType;
  typedef InventoryItemEntryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4,
    VT_GRID_X = 6,
    VT_GRID_Y = 8,
    VT_ROTATED = 10,
    VT_STACK_COUNT = 12
  };
  const ::flatbuffers::String *item_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ITEM_ID);
  }
  int16_t grid_x() const {
    return GetField<int16_t>(VT_GRID_X, 0);
  }
  int16_t grid_y() const {
    return GetField<int16_t>(VT_GRID_Y, 0);
  }
  bool rotated() const {
    return GetField<uint8_t>(VT_ROTATED, 0) != 0;
  }
  int16_t stack_count() const {
    return GetField<int16_t>(VT_STACK_COUNT, 1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEM_ID) &&
           verifier.VerifyString(item_id()) &&
           VerifyField<int16_t>(verifier, VT_GRID_X, 2) &&
           VerifyField<int16_t>(verifier, VT_GRID_Y, 2) &&
           VerifyField<uint8_t>(verifier, VT_ROTATED, 1) &&
           VerifyField<int16_t>(verifier, VT_STACK_COUNT, 2) &&
           verifier.EndTable();
  }
  InventoryItemEntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(InventoryItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<InventoryItemEntry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InventoryItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct InventoryItemEntryBuilder {
  typedef InventoryItemEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_item_id(::flatbuffers::Offset<::flatbuffers::String> item_id) {
    fbb_.AddOffset(InventoryItemEntry::VT_ITEM_ID, item_id);
  }
  void add_grid_x(int16_t grid_x) {
    fbb_.AddElement<int16_t>(InventoryItemEntry::VT_GRID_X, grid_x, 0);
  }
  void add_grid_y(int16_t grid_y) {
    fbb_.AddElement<int16_t>(InventoryItemEntry::VT_GRID_Y, grid_y, 0);
  }
  void add_rotated(bool rotated) {
    fbb_.AddElement<uint8_t>(InventoryItemEntry::VT_ROTATED, static_cast<uint8_t>(rotated), 0);
  }
  void add_stack_count(int16_t stack_count) {
    fbb_.AddElement<int16_t>(InventoryItemEntry::VT_STACK_COUNT, stack_count, 1);
  }
  explicit InventoryItemEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InventoryItemEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InventoryItemEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<InventoryItemEntry> CreateInventoryItemEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> item_id = 0,
    int16_t grid_x = 0,
    int16_t grid_y = 0,
    bool rotated = false,
    int16_t stack_count = 1) {
  InventoryItemEntryBuilder builder_(_fbb);
  builder_.add_item_id(item_id);
  builder_.add_stack_count(stack_count);
  builder_.add_grid_y(grid_y);
  builder_.add_grid_x(grid_x);
  builder_.add_rotated(rotated);
  return builder_.Finish();
}

struct InventoryItemEntry::Traits {
  using type = InventoryItemEntry;
  static auto constexpr Create = CreateInventoryItemEntry;
};

inline ::flatbuffers::Offset<InventoryItemEntry> CreateInventoryItemEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *item_id = nullptr,
    int16_t grid_x = 0,
    int16_t grid_y = 0,
    bool rotated = false,
    int16_t stack_count = 1) {
  auto item_id__ = item_id ? _fbb.CreateString(item_id) : 0;
  return ProtoType::Net::CreateInventoryItemEntry(
      _fbb,
      item_id__,
      grid_x,
      grid_y,
      rotated,
      stack_count);
}

::flatbuffers::Offset<InventoryItemEntry> CreateInventoryItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const InventoryItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_SaveInventoryT : public ::flatbuffers::NativeTable {
  typedef C2S_SaveInventory TableType;
  std::vector<std::unique_ptr<ProtoType::Net::InventoryItemEntryT>> items{};
  C2S_SaveInventoryT() = default;
  C2S_SaveInventoryT(const C2S_SaveInventoryT &o);
  C2S_SaveInventoryT(C2S_SaveInventoryT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_SaveInventoryT &operator=(C2S_SaveInventoryT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_SaveInventory FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_SaveInventoryT NativeTableType;
  typedef C2S_SaveInventoryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_SaveInventoryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_SaveInventoryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_SaveInventory> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveInventoryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_SaveInventoryBuilder {
  typedef C2S_SaveInventory Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items) {
    fbb_.AddOffset(C2S_SaveInventory::VT_ITEMS, items);
  }
  explicit C2S_SaveInventoryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_SaveInventory> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_SaveInventory>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_SaveInventory> CreateC2S_SaveInventory(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items = 0) {
  C2S_SaveInventoryBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

struct C2S_SaveInventory::Traits {
  using type = C2S_SaveInventory;
  static auto constexpr Create = CreateC2S_SaveInventory;
};

inline ::flatbuffers::Offset<C2S_SaveInventory> CreateC2S_SaveInventoryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_SaveInventory(
      _fbb,
      items__);
}

::flatbuffers::Offset<C2S_SaveInventory> CreateC2S_SaveInventory(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveInventoryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct EquipmentItemEntryT : public ::flatbuffers::NativeTable {
  typedef EquipmentItemEntry TableType;
  uint8_t slot = 0;
  std::string item_id{};
};

struct EquipmentItemEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EquipmentItemEntryT NativeTableType;
  typedef EquipmentItemEntryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SLOT = 4,
    VT_ITEM_ID = 6
  };
  uint8_t slot() const {
    return GetField<uint8_t>(VT_SLOT, 0);
  }
  const ::flatbuffers::String *item_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ITEM_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SLOT, 1) &&
           VerifyOffset(verifier, VT_ITEM_ID) &&
           verifier.VerifyString(item_id()) &&
           verifier.EndTable();
  }
  EquipmentItemEntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EquipmentItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EquipmentItemEntry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EquipmentItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EquipmentItemEntryBuilder {
  typedef EquipmentItemEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_slot(uint8_t slot) {
    fbb_.AddElement<uint8_t>(EquipmentItemEntry::VT_SLOT, slot, 0);
  }
  void add_item_id(::flatbuffers::Offset<::flatbuffers::String> item_id) {
    fbb_.AddOffset(EquipmentItemEntry::VT_ITEM_ID, item_id);
  }
  explicit EquipmentItemEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EquipmentItemEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EquipmentItemEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EquipmentItemEntry> CreateEquipmentItemEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t slot = 0,
    ::flatbuffers::Offset<::flatbuffers::String> item_id = 0) {
  EquipmentItemEntryBuilder builder_(_fbb);
  builder_.add_item_id(item_id);
  builder_.add_slot(slot);
  return builder_.Finish();
}

struct EquipmentItemEntry::Traits {
  using type = EquipmentItemEntry;
  static auto constexpr Create = CreateEquipmentItemEntry;
};

inline ::flatbuffers::Offset<EquipmentItemEntry> CreateEquipmentItemEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t slot = 0,
    const char *item_id = nullptr) {
  auto item_id__ = item_id ? _fbb.CreateString(item_id) : 0;
  return ProtoType::Net::CreateEquipmentItemEntry(
      _fbb,
      slot,
      item_id__);
}

::flatbuffers::Offset<EquipmentItemEntry> CreateEquipmentItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const EquipmentItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_SaveEquipmentT : public ::flatbuffers::NativeTable {
  typedef C2S_SaveEquipment TableType;
  std::vector<std::unique_ptr<ProtoType::Net::EquipmentItemEntryT>> items{};
  C2S_SaveEquipmentT() = default;
  C2S_SaveEquipmentT(const C2S_SaveEquipmentT &o);
  C2S_SaveEquipmentT(C2S_SaveEquipmentT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_SaveEquipmentT &operator=(C2S_SaveEquipmentT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_SaveEquipment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_SaveEquipmentT NativeTableType;
  typedef C2S_SaveEquipmentBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_SaveEquipmentT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_SaveEquipmentT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_SaveEquipment> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveEquipmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_SaveEquipmentBuilder {
  typedef C2S_SaveEquipment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>>> items) {
    fbb_.AddOffset(C2S_SaveEquipment::VT_ITEMS, items);
  }
  explicit C2S_SaveEquipmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_SaveEquipment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_SaveEquipment>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_SaveEquipment> CreateC2S_SaveEquipment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>>> items = 0) {
  C2S_SaveEquipmentBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

struct C2S_SaveEquipment::Traits {
  using type = C2S_SaveEquipment;
  static auto constexpr Create = CreateC2S_SaveEquipment;
};

inline ::flatbuffers::Offset<C2S_SaveEquipment> CreateC2S_SaveEquipmentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_SaveEquipment(
      _fbb,
      items__);
}

::flatbuffers::Offset<C2S_SaveEquipment> CreateC2S_SaveEquipment(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveEquipmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct QuickSlotItemEntryT : public ::flatbuffers::NativeTable {
  typedef QuickSlotItemEntry TableType;
  uint8_t slot_index = 0;
  std::string item_id{};
  int16_t stack_count = 1;
};

struct QuickSlotItemEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuickSlotItemEntryT NativeTableType;
  typedef QuickSlotItemEntryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SLOT_INDEX = 4,
    VT_ITEM_ID = 6,
    VT_STACK_COUNT = 8
  };
  uint8_t slot_index() const {
    return GetField<uint8_t>(VT_SLOT_INDEX, 0);
  }
  const ::flatbuffers::String *item_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ITEM_ID);
  }
  int16_t stack_count() const {
    return GetField<int16_t>(VT_STACK_COUNT, 1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SLOT_INDEX, 1) &&
           VerifyOffset(verifier, VT_ITEM_ID) &&
           verifier.VerifyString(item_id()) &&
           VerifyField<int16_t>(verifier, VT_STACK_COUNT, 2) &&
           verifier.EndTable();
  }
  QuickSlotItemEntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(QuickSlotItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<QuickSlotItemEntry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuickSlotItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct QuickSlotItemEntryBuilder {
  typedef QuickSlotItemEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_slot_index(uint8_t slot_index) {
    fbb_.AddElement<uint8_t>(QuickSlotItemEntry::VT_SLOT_INDEX, slot_index, 0);
  }
  void add_item_id(::flatbuffers::Offset<::flatbuffers::String> item_id) {
    fbb_.AddOffset(QuickSlotItemEntry::VT_ITEM_ID, item_id);
  }
  void add_stack_count(int16_t stack_count) {
    fbb_.AddElement<int16_t>(QuickSlotItemEntry::VT_STACK_COUNT, stack_count, 1);
  }
  explicit QuickSlotItemEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<QuickSlotItemEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<QuickSlotItemEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<QuickSlotItemEntry> CreateQuickSlotItemEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t slot_index = 0,
    ::flatbuffers::Offset<::flatbuffers::String> item_id = 0,
    int16_t stack_count = 1) {
  QuickSlotItemEntryBuilder builder_(_fbb);
  builder_.add_item_id(item_id);
  builder_.add_stack_count(stack_count);
  builder_.add_slot_index(slot_index);
  return builder_.Finish();
}

struct QuickSlotItemEntry::Traits {
  using type = QuickSlotItemEntry;
  static auto constexpr Create = CreateQuickSlotItemEntry;
};

inline ::flatbuffers::Offset<QuickSlotItemEntry> CreateQuickSlotItemEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t slot_index = 0,
    const char *item_id = nullptr,
    int16_t stack_count = 1) {
  auto item_id__ = item_id ? _fbb.CreateString(item_id) : 0;
  return ProtoType::Net::CreateQuickSlotItemEntry(
      _fbb,
      slot_index,
      item_id__,
      stack_count);
}

::flatbuffers::Offset<QuickSlotItemEntry> CreateQuickSlotItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const QuickSlotItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_SaveQuickSlotsT : public ::flatbuffers::NativeTable {
  typedef C2S_SaveQuickSlots TableType;
  std::vector<std::unique_ptr<ProtoType::Net::QuickSlotItemEntryT>> items{};
  C2S_SaveQuickSlotsT() = default;
  C2S_SaveQuickSlotsT(const C2S_SaveQuickSlotsT &o);
  C2S_SaveQuickSlotsT(C2S_SaveQuickSlotsT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_SaveQuickSlotsT &operator=(C2S_SaveQuickSlotsT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_SaveQuickSlots FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_SaveQuickSlotsT NativeTableType;
  typedef C2S_SaveQuickSlotsBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_SaveQuickSlotsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_SaveQuickSlotsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_SaveQuickSlots> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveQuickSlotsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_SaveQuickSlotsBuilder {
  typedef C2S_SaveQuickSlots Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>>> items) {
    fbb_.AddOffset(C2S_SaveQuickSlots::VT_ITEMS, items);
  }
  explicit C2S_SaveQuickSlotsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_SaveQuickSlots> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_SaveQuickSlots>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_SaveQuickSlots> CreateC2S_SaveQuickSlots(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>>> items = 0) {
  C2S_SaveQuickSlotsBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

struct C2S_SaveQuickSlots::Traits {
  using type = C2S_SaveQuickSlots;
  static auto constexpr Create = CreateC2S_SaveQuickSlots;
};

inline ::flatbuffers::Offset<C2S_SaveQuickSlots> CreateC2S_SaveQuickSlotsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_SaveQuickSlots(
      _fbb,
      items__);
}

::flatbuffers::Offset<C2S_SaveQuickSlots> CreateC2S_SaveQuickSlots(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveQuickSlotsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_RequestStashT : public ::flatbuffers::NativeTable {
  typedef C2S_RequestStash TableType;
};

struct C2S_RequestStash FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_RequestStashT NativeTableType;
  typedef C2S_RequestStashBuilder Builder;
  struct Traits;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  C2S_RequestStashT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_RequestStashT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_RequestStash> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestStashT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_RequestStashBuilder {
  typedef C2S_RequestStash Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C2S_RequestStashBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_RequestStash> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_RequestStash>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_RequestStash> CreateC2S_RequestStash(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C2S_RequestStashBuilder builder_(_fbb);
  return builder_.Finish();
}

struct C2S_RequestStash::Traits {
  using type = C2S_RequestStash;
  static auto constexpr Create = CreateC2S_RequestStash;
};

::flatbuffers::Offset<C2S_RequestStash> CreateC2S_RequestStash(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestStashT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_StashStateT : public ::flatbuffers::NativeTable {
  typedef S2C_StashState TableType;
  std::vector<std::unique_ptr<ProtoType::Net::InventoryItemEntryT>> items{};
  S2C_StashStateT() = default;
  S2C_StashStateT(const S2C_StashStateT &o);
  S2C_StashStateT(S2C_StashStateT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_StashStateT &operator=(S2C_StashStateT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_StashState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_StashStateT NativeTableType;
  typedef S2C_StashStateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  S2C_StashStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_StashStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_StashState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_StashStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_StashStateBuilder {
  typedef S2C_StashState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items) {
    fbb_.AddOffset(S2C_StashState::VT_ITEMS, items);
  }
  explicit S2C_StashStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_StashState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_StashState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_StashState> CreateS2C_StashState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items = 0) {
  S2C_StashStateBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

struct S2C_StashState::Traits {
  using type = S2C_StashState;
  static auto constexpr Create = CreateS2C_StashState;
};

inline ::flatbuffers::Offset<S2C_StashState> CreateS2C_StashStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateS2C_StashState(
      _fbb,
      items__);
}

::flatbuffers::Offset<S2C_StashState> CreateS2C_StashState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_StashStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_SaveStashT : public ::flatbuffers::NativeTable {
  typedef C2S_SaveStash TableType;
  std::vector<std::unique_ptr<ProtoType::Net::InventoryItemEntryT>> items{};
  C2S_SaveStashT() = default;
  C2S_SaveStashT(const C2S_SaveStashT &o);
  C2S_SaveStashT(C2S_SaveStashT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_SaveStashT &operator=(C2S_SaveStashT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_SaveStash FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_SaveStashT NativeTableType;
  typedef C2S_SaveStashBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_SaveStashT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_SaveStashT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_SaveStash> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveStashT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_SaveStashBuilder {
  typedef C2S_SaveStash Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items) {
    fbb_.AddOffset(C2S_SaveStash::VT_ITEMS, items);
  }
  explicit C2S_SaveStashBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_SaveStash> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_SaveStash>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_SaveStash> CreateC2S_SaveStash(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items = 0) {
  C2S_SaveStashBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

struct C2S_SaveStash::Traits {
  using type = C2S_SaveStash;
  static auto constexpr Create = CreateC2S_SaveStash;
};

inline ::flatbuffers::Offset<C2S_SaveStash> CreateC2S_SaveStashDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_SaveStash(
      _fbb,
      items__);
}

::flatbuffers::Offset<C2S_SaveStash> CreateC2S_SaveStash(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveStashT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline InventoryItemEntryT *InventoryItemEntry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<InventoryItemEntryT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void InventoryItemEntry::UnPackTo(InventoryItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = item_id(); if (_e) _o->item_id = _e->str(); }
  { auto _e = grid_x(); _o->grid_x = _e; }
  { auto _e = grid_y(); _o->grid_y = _e; }
  { auto _e = rotated(); _o->rotated = _e; }
  { auto _e = stack_count(); _o->stack_count = _e; }
}

inline ::flatbuffers::Offset<InventoryItemEntry> CreateInventoryItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const InventoryItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return InventoryItemEntry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<InventoryItemEntry> InventoryItemEntry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const InventoryItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const InventoryItemEntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _item_id = _o->item_id.empty() ? 0 : _fbb.CreateString(_o->item_id);
  auto _grid_x = _o->grid_x;
  auto _grid_y = _o->grid_y;
  auto _rotated = _o->rotated;
  auto _stack_count = _o->stack_count;
  return ProtoType::Net::CreateInventoryItemEntry(
      _fbb,
      _item_id,
      _grid_x,
      _grid_y,
      _rotated,
      _stack_count);
}

inline C2S_SaveInventoryT::C2S_SaveInventoryT(const C2S_SaveInventoryT &o) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::InventoryItemEntryT(*items_) : nullptr); }
}

inline C2S_SaveInventoryT &C2S_SaveInventoryT::operator=(C2S_SaveInventoryT o) FLATBUFFERS_NOEXCEPT {
  std::swap(items, o.items);
  return *this;
}

inline C2S_SaveInventoryT *C2S_SaveInventory::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_SaveInventoryT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_SaveInventory::UnPackTo(C2S_SaveInventoryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::InventoryItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_SaveInventory> CreateC2S_SaveInventory(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveInventoryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_SaveInventory::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_SaveInventory> C2S_SaveInventory::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveInventoryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_SaveInventoryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateInventoryItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_SaveInventory(
      _fbb,
      _items);
}

inline EquipmentItemEntryT *EquipmentItemEntry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<EquipmentItemEntryT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EquipmentItemEntry::UnPackTo(EquipmentItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = slot(); _o->slot = _e; }
  { auto _e = item_id(); if (_e) _o->item_id = _e->str(); }
}

inline ::flatbuffers::Offset<EquipmentItemEntry> CreateEquipmentItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const EquipmentItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return EquipmentItemEntry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EquipmentItemEntry> EquipmentItemEntry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EquipmentItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EquipmentItemEntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _slot = _o->slot;
  auto _item_id = _o->item_id.empty() ? 0 : _fbb.CreateString(_o->item_id);
  return ProtoType::Net::CreateEquipmentItemEntry(
      _fbb,
      _slot,
      _item_id);
}

inline C2S_SaveEquipmentT::C2S_SaveEquipmentT(const C2S_SaveEquipmentT &o) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::EquipmentItemEntryT(*items_) : nullptr); }
}

inline C2S_SaveEquipmentT &C2S_SaveEquipmentT::operator=(C2S_SaveEquipmentT o) FLATBUFFERS_NOEXCEPT {
  std::swap(items, o.items);
  return *this;
}

inline C2S_SaveEquipmentT *C2S_SaveEquipment::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_SaveEquipmentT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_SaveEquipment::UnPackTo(C2S_SaveEquipmentT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::EquipmentItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_SaveEquipment> CreateC2S_SaveEquipment(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveEquipmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_SaveEquipment::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_SaveEquipment> C2S_SaveEquipment::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveEquipmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_SaveEquipmentT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquipmentItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateEquipmentItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_SaveEquipment(
      _fbb,
      _items);
}

inline QuickSlotItemEntryT *QuickSlotItemEntry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<QuickSlotItemEntryT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void QuickSlotItemEntry::UnPackTo(QuickSlotItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = slot_index(); _o->slot_index = _e; }
  { auto _e = item_id(); if (_e) _o->item_id = _e->str(); }
  { auto _e = stack_count(); _o->stack_count = _e; }
}

inline ::flatbuffers::Offset<QuickSlotItemEntry> CreateQuickSlotItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const QuickSlotItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return QuickSlotItemEntry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<QuickSlotItemEntry> QuickSlotItemEntry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const QuickSlotItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const QuickSlotItemEntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _slot_index = _o->slot_index;
  auto _item_id = _o->item_id.empty() ? 0 : _fbb.CreateString(_o->item_id);
  auto _stack_count = _o->stack_count;
  return ProtoType::Net::CreateQuickSlotItemEntry(
      _fbb,
      _slot_index,
      _item_id,
      _stack_count);
}

inline C2S_SaveQuickSlotsT::C2S_SaveQuickSlotsT(const C2S_SaveQuickSlotsT &o) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::QuickSlotItemEntryT(*items_) : nullptr); }
}

inline C2S_SaveQuickSlotsT &C2S_SaveQuickSlotsT::operator=(C2S_SaveQuickSlotsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(items, o.items);
  return *this;
}

inline C2S_SaveQuickSlotsT *C2S_SaveQuickSlots::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_SaveQuickSlotsT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_SaveQuickSlots::UnPackTo(C2S_SaveQuickSlotsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::QuickSlotItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_SaveQuickSlots> CreateC2S_SaveQuickSlots(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveQuickSlotsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_SaveQuickSlots::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_SaveQuickSlots> C2S_SaveQuickSlots::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveQuickSlotsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_SaveQuickSlotsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::QuickSlotItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateQuickSlotItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_SaveQuickSlots(
      _fbb,
      _items);
}

inline C2S_RequestStashT *C2S_RequestStash::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_RequestStashT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_RequestStash::UnPackTo(C2S_RequestStashT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<C2S_RequestStash> CreateC2S_RequestStash(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestStashT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_RequestStash::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_RequestStash> C2S_RequestStash::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestStashT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_RequestStashT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return ProtoType::Net::CreateC2S_RequestStash(
      _fbb);
}

inline S2C_StashStateT::S2C_StashStateT(const S2C_StashStateT &o) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::InventoryItemEntryT(*items_) : nullptr); }
}

inline S2C_StashStateT &S2C_StashStateT::operator=(S2C_StashStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(items, o.items);
  return *this;
}

inline S2C_StashStateT *S2C_StashState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_StashStateT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_StashState::UnPackTo(S2C_StashStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::InventoryItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<S2C_StashState> CreateS2C_StashState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_StashStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_StashState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_StashState> S2C_StashState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_StashStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_StashStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateInventoryItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateS2C_StashState(
      _fbb,
      _items);
}

inline C2S_SaveStashT::C2S_SaveStashT(const C2S_SaveStashT &o) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::InventoryItemEntryT(*items_) : nullptr); }
}

inline C2S_SaveStashT &C2S_SaveStashT::operator=(C2S_SaveStashT o) FLATBUFFERS_NOEXCEPT {
  std::swap(items, o.items);
  return *this;
}

inline C2S_SaveStashT *C2S_SaveStash::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_SaveStashT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_SaveStash::UnPackTo(C2S_SaveStashT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::InventoryItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_SaveStash> CreateC2S_SaveStash(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveStashT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_SaveStash::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_SaveStash> C2S_SaveStash::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_SaveStashT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_SaveStashT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateInventoryItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_SaveStash(
      _fbb,
      _items);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_INVENTORY_PROTOTYPE_NET_H_
