// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"
#include "inventory.h"

namespace ProtoType {
namespace Net {

struct C2S_ItemUseRequest;
struct C2S_ItemUseRequestBuilder;
struct C2S_ItemUseRequestT;

struct S2C_ItemUseResult;
struct S2C_ItemUseResultBuilder;
struct S2C_ItemUseResultT;

struct S2C_ItemUseBroadcast;
struct S2C_ItemUseBroadcastBuilder;
struct S2C_ItemUseBroadcastT;

struct C2S_ContainerLootRoll;
struct C2S_ContainerLootRollBuilder;
struct C2S_ContainerLootRollT;

struct S2C_ContainerLootState;
struct S2C_ContainerLootStateBuilder;
struct S2C_ContainerLootStateT;

struct WorldSpawnedItemEntry;
struct WorldSpawnedItemEntryBuilder;
struct WorldSpawnedItemEntryT;

struct C2S_ItemSpawnRoll;
struct C2S_ItemSpawnRollBuilder;
struct C2S_ItemSpawnRollT;

struct S2C_ItemSpawnState;
struct S2C_ItemSpawnStateBuilder;
struct S2C_ItemSpawnStateT;

enum class ItemUseType : int8_t {
  Consume = 0,
  Equip = 1,
  Unequip = 2,
  Drop = 3,
  Reload = 4,
  Inspect = 5,
  ToggleAttachment = 6,
  MIN = Consume,
  MAX = ToggleAttachment
};

inline const ItemUseType (&EnumValuesItemUseType())[7] {
  static const ItemUseType values[] = {
    ItemUseType::Consume,
    ItemUseType::Equip,
    ItemUseType::Unequip,
    ItemUseType::Drop,
    ItemUseType::Reload,
    ItemUseType::Inspect,
    ItemUseType::ToggleAttachment
  };
  return values;
}

inline const char * const *EnumNamesItemUseType() {
  static const char * const names[8] = {
    "Consume",
    "Equip",
    "Unequip",
    "Drop",
    "Reload",
    "Inspect",
    "ToggleAttachment",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemUseType(ItemUseType e) {
  if (::flatbuffers::IsOutRange(e, ItemUseType::Consume, ItemUseType::ToggleAttachment)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemUseType()[index];
}

struct C2S_ItemUseRequestT : public ::flatbuffers::NativeTable {
  typedef C2S_ItemUseRequest TableType;
  std::unique_ptr<ProtoType::Net::Header> header{};
  uint64_t item_instance_id = 0;
  uint8_t slot = 0;
  ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume;
  C2S_ItemUseRequestT() = default;
  C2S_ItemUseRequestT(const C2S_ItemUseRequestT &o);
  C2S_ItemUseRequestT(C2S_ItemUseRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_ItemUseRequestT &operator=(C2S_ItemUseRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_ItemUseRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_ItemUseRequestT NativeTableType;
  typedef C2S_ItemUseRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_ITEM_INSTANCE_ID = 6,
    VT_SLOT = 8,
    VT_USE_TYPE = 10
  };
  const ProtoType::Net::Header *header() const {
    return GetStruct<const ProtoType::Net::Header *>(VT_HEADER);
  }
  uint64_t item_instance_id() const {
    return GetField<uint64_t>(VT_ITEM_INSTANCE_ID, 0);
  }
  uint8_t slot() const {
    return GetField<uint8_t>(VT_SLOT, 0);
  }
  ProtoType::Net::ItemUseType use_type() const {
    return static_cast<ProtoType::Net::ItemUseType>(GetField<int8_t>(VT_USE_TYPE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ProtoType::Net::Header>(verifier, VT_HEADER, 4) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_INSTANCE_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_SLOT, 1) &&
           VerifyField<int8_t>(verifier, VT_USE_TYPE, 1) &&
           verifier.EndTable();
  }
  C2S_ItemUseRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_ItemUseRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_ItemUseRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_ItemUseRequestBuilder {
  typedef C2S_ItemUseRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(const ProtoType::Net::Header *header) {
    fbb_.AddStruct(C2S_ItemUseRequest::VT_HEADER, header);
  }
  void add_item_instance_id(uint64_t item_instance_id) {
    fbb_.AddElement<uint64_t>(C2S_ItemUseRequest::VT_ITEM_INSTANCE_ID, item_instance_id, 0);
  }
  void add_slot(uint8_t slot) {
    fbb_.AddElement<uint8_t>(C2S_ItemUseRequest::VT_SLOT, slot, 0);
  }
  void add_use_type(ProtoType::Net::ItemUseType use_type) {
    fbb_.AddElement<int8_t>(C2S_ItemUseRequest::VT_USE_TYPE, static_cast<int8_t>(use_type), 0);
  }
  explicit C2S_ItemUseRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_ItemUseRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_ItemUseRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ProtoType::Net::Header *header = nullptr,
    uint64_t item_instance_id = 0,
    uint8_t slot = 0,
    ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume) {
  C2S_ItemUseRequestBuilder builder_(_fbb);
  builder_.add_item_instance_id(item_instance_id);
  builder_.add_header(header);
  builder_.add_use_type(use_type);
  builder_.add_slot(slot);
  return builder_.Finish();
}

struct C2S_ItemUseRequest::Traits {
  using type = C2S_ItemUseRequest;
  static auto constexpr Create = CreateC2S_ItemUseRequest;
};

::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_ItemUseResultT : public ::flatbuffers::NativeTable {
  typedef S2C_ItemUseResult TableType;
  uint32_t player_id = 0;
  uint64_t item_instance_id = 0;
  ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume;
  ProtoType::Net::ResultCode result = ProtoType::Net::ResultCode::Ok;
  float value = 0.0f;
};

struct S2C_ItemUseResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_ItemUseResultT NativeTableType;
  typedef S2C_ItemUseResultBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_ITEM_INSTANCE_ID = 6,
    VT_USE_TYPE = 8,
    VT_RESULT = 10,
    VT_VALUE = 12
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint64_t item_instance_id() const {
    return GetField<uint64_t>(VT_ITEM_INSTANCE_ID, 0);
  }
  ProtoType::Net::ItemUseType use_type() const {
    return static_cast<ProtoType::Net::ItemUseType>(GetField<int8_t>(VT_USE_TYPE, 0));
  }
  ProtoType::Net::ResultCode result() const {
    return static_cast<ProtoType::Net::ResultCode>(GetField<int8_t>(VT_RESULT, 0));
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_INSTANCE_ID, 8) &&
           VerifyField<int8_t>(verifier, VT_USE_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_RESULT, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
  S2C_ItemUseResultT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_ItemUseResultT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_ItemUseResult> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_ItemUseResultBuilder {
  typedef S2C_ItemUseResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(S2C_ItemUseResult::VT_PLAYER_ID, player_id, 0);
  }
  void add_item_instance_id(uint64_t item_instance_id) {
    fbb_.AddElement<uint64_t>(S2C_ItemUseResult::VT_ITEM_INSTANCE_ID, item_instance_id, 0);
  }
  void add_use_type(ProtoType::Net::ItemUseType use_type) {
    fbb_.AddElement<int8_t>(S2C_ItemUseResult::VT_USE_TYPE, static_cast<int8_t>(use_type), 0);
  }
  void add_result(ProtoType::Net::ResultCode result) {
    fbb_.AddElement<int8_t>(S2C_ItemUseResult::VT_RESULT, static_cast<int8_t>(result), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(S2C_ItemUseResult::VT_VALUE, value, 0.0f);
  }
  explicit S2C_ItemUseResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_ItemUseResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_ItemUseResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint64_t item_instance_id = 0,
    ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume,
    ProtoType::Net::ResultCode result = ProtoType::Net::ResultCode::Ok,
    float value = 0.0f) {
  S2C_ItemUseResultBuilder builder_(_fbb);
  builder_.add_item_instance_id(item_instance_id);
  builder_.add_value(value);
  builder_.add_player_id(player_id);
  builder_.add_result(result);
  builder_.add_use_type(use_type);
  return builder_.Finish();
}

struct S2C_ItemUseResult::Traits {
  using type = S2C_ItemUseResult;
  static auto constexpr Create = CreateS2C_ItemUseResult;
};

::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_ItemUseBroadcastT : public ::flatbuffers::NativeTable {
  typedef S2C_ItemUseBroadcast TableType;
  uint32_t user_id = 0;
  ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume;
  uint8_t slot = 0;
};

struct S2C_ItemUseBroadcast FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_ItemUseBroadcastT NativeTableType;
  typedef S2C_ItemUseBroadcastBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER_ID = 4,
    VT_USE_TYPE = 6,
    VT_SLOT = 8
  };
  uint32_t user_id() const {
    return GetField<uint32_t>(VT_USER_ID, 0);
  }
  ProtoType::Net::ItemUseType use_type() const {
    return static_cast<ProtoType::Net::ItemUseType>(GetField<int8_t>(VT_USE_TYPE, 0));
  }
  uint8_t slot() const {
    return GetField<uint8_t>(VT_SLOT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_USER_ID, 4) &&
           VerifyField<int8_t>(verifier, VT_USE_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_SLOT, 1) &&
           verifier.EndTable();
  }
  S2C_ItemUseBroadcastT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_ItemUseBroadcastT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_ItemUseBroadcast> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseBroadcastT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_ItemUseBroadcastBuilder {
  typedef S2C_ItemUseBroadcast Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_user_id(uint32_t user_id) {
    fbb_.AddElement<uint32_t>(S2C_ItemUseBroadcast::VT_USER_ID, user_id, 0);
  }
  void add_use_type(ProtoType::Net::ItemUseType use_type) {
    fbb_.AddElement<int8_t>(S2C_ItemUseBroadcast::VT_USE_TYPE, static_cast<int8_t>(use_type), 0);
  }
  void add_slot(uint8_t slot) {
    fbb_.AddElement<uint8_t>(S2C_ItemUseBroadcast::VT_SLOT, slot, 0);
  }
  explicit S2C_ItemUseBroadcastBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_ItemUseBroadcast> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_ItemUseBroadcast>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_ItemUseBroadcast> CreateS2C_ItemUseBroadcast(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t user_id = 0,
    ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume,
    uint8_t slot = 0) {
  S2C_ItemUseBroadcastBuilder builder_(_fbb);
  builder_.add_user_id(user_id);
  builder_.add_slot(slot);
  builder_.add_use_type(use_type);
  return builder_.Finish();
}

struct S2C_ItemUseBroadcast::Traits {
  using type = S2C_ItemUseBroadcast;
  static auto constexpr Create = CreateS2C_ItemUseBroadcast;
};

::flatbuffers::Offset<S2C_ItemUseBroadcast> CreateS2C_ItemUseBroadcast(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseBroadcastT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_ContainerLootRollT : public ::flatbuffers::NativeTable {
  typedef C2S_ContainerLootRoll TableType;
  uint32_t container_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::InventoryItemEntryT>> items{};
  C2S_ContainerLootRollT() = default;
  C2S_ContainerLootRollT(const C2S_ContainerLootRollT &o);
  C2S_ContainerLootRollT(C2S_ContainerLootRollT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_ContainerLootRollT &operator=(C2S_ContainerLootRollT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_ContainerLootRoll FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_ContainerLootRollT NativeTableType;
  typedef C2S_ContainerLootRollBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTAINER_ID = 4,
    VT_ITEMS = 6
  };
  uint32_t container_id() const {
    return GetField<uint32_t>(VT_CONTAINER_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CONTAINER_ID, 4) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_ContainerLootRollT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_ContainerLootRollT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_ContainerLootRoll> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ContainerLootRollT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_ContainerLootRollBuilder {
  typedef C2S_ContainerLootRoll Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_container_id(uint32_t container_id) {
    fbb_.AddElement<uint32_t>(C2S_ContainerLootRoll::VT_CONTAINER_ID, container_id, 0);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items) {
    fbb_.AddOffset(C2S_ContainerLootRoll::VT_ITEMS, items);
  }
  explicit C2S_ContainerLootRollBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_ContainerLootRoll> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_ContainerLootRoll>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_ContainerLootRoll> CreateC2S_ContainerLootRoll(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t container_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items = 0) {
  C2S_ContainerLootRollBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_container_id(container_id);
  return builder_.Finish();
}

struct C2S_ContainerLootRoll::Traits {
  using type = C2S_ContainerLootRoll;
  static auto constexpr Create = CreateC2S_ContainerLootRoll;
};

inline ::flatbuffers::Offset<C2S_ContainerLootRoll> CreateC2S_ContainerLootRollDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t container_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_ContainerLootRoll(
      _fbb,
      container_id,
      items__);
}

::flatbuffers::Offset<C2S_ContainerLootRoll> CreateC2S_ContainerLootRoll(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ContainerLootRollT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_ContainerLootStateT : public ::flatbuffers::NativeTable {
  typedef S2C_ContainerLootState TableType;
  uint32_t container_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::InventoryItemEntryT>> items{};
  S2C_ContainerLootStateT() = default;
  S2C_ContainerLootStateT(const S2C_ContainerLootStateT &o);
  S2C_ContainerLootStateT(S2C_ContainerLootStateT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_ContainerLootStateT &operator=(S2C_ContainerLootStateT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_ContainerLootState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_ContainerLootStateT NativeTableType;
  typedef S2C_ContainerLootStateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTAINER_ID = 4,
    VT_ITEMS = 6
  };
  uint32_t container_id() const {
    return GetField<uint32_t>(VT_CONTAINER_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CONTAINER_ID, 4) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  S2C_ContainerLootStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_ContainerLootStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_ContainerLootState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ContainerLootStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_ContainerLootStateBuilder {
  typedef S2C_ContainerLootState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_container_id(uint32_t container_id) {
    fbb_.AddElement<uint32_t>(S2C_ContainerLootState::VT_CONTAINER_ID, container_id, 0);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items) {
    fbb_.AddOffset(S2C_ContainerLootState::VT_ITEMS, items);
  }
  explicit S2C_ContainerLootStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_ContainerLootState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_ContainerLootState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_ContainerLootState> CreateS2C_ContainerLootState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t container_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>> items = 0) {
  S2C_ContainerLootStateBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_container_id(container_id);
  return builder_.Finish();
}

struct S2C_ContainerLootState::Traits {
  using type = S2C_ContainerLootState;
  static auto constexpr Create = CreateS2C_ContainerLootState;
};

inline ::flatbuffers::Offset<S2C_ContainerLootState> CreateS2C_ContainerLootStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t container_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateS2C_ContainerLootState(
      _fbb,
      container_id,
      items__);
}

::flatbuffers::Offset<S2C_ContainerLootState> CreateS2C_ContainerLootState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ContainerLootStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct WorldSpawnedItemEntryT : public ::flatbuffers::NativeTable {
  typedef WorldSpawnedItemEntry TableType;
  std::string item_id{};
  std::unique_ptr<ProtoType::Net::Vec3> position{};
  int16_t stack_count = 1;
  WorldSpawnedItemEntryT() = default;
  WorldSpawnedItemEntryT(const WorldSpawnedItemEntryT &o);
  WorldSpawnedItemEntryT(WorldSpawnedItemEntryT&&) FLATBUFFERS_NOEXCEPT = default;
  WorldSpawnedItemEntryT &operator=(WorldSpawnedItemEntryT o) FLATBUFFERS_NOEXCEPT;
};

struct WorldSpawnedItemEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldSpawnedItemEntryT NativeTableType;
  typedef WorldSpawnedItemEntryBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEM_ID = 4,
    VT_POSITION = 6,
    VT_STACK_COUNT = 8
  };
  const ::flatbuffers::String *item_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ITEM_ID);
  }
  const ProtoType::Net::Vec3 *position() const {
    return GetStruct<const ProtoType::Net::Vec3 *>(VT_POSITION);
  }
  int16_t stack_count() const {
    return GetField<int16_t>(VT_STACK_COUNT, 1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEM_ID) &&
           verifier.VerifyString(item_id()) &&
           VerifyField<ProtoType::Net::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<int16_t>(verifier, VT_STACK_COUNT, 2) &&
           verifier.EndTable();
  }
  WorldSpawnedItemEntryT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(WorldSpawnedItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<WorldSpawnedItemEntry> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const WorldSpawnedItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct WorldSpawnedItemEntryBuilder {
  typedef WorldSpawnedItemEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_item_id(::flatbuffers::Offset<::flatbuffers::String> item_id) {
    fbb_.AddOffset(WorldSpawnedItemEntry::VT_ITEM_ID, item_id);
  }
  void add_position(const ProtoType::Net::Vec3 *position) {
    fbb_.AddStruct(WorldSpawnedItemEntry::VT_POSITION, position);
  }
  void add_stack_count(int16_t stack_count) {
    fbb_.AddElement<int16_t>(WorldSpawnedItemEntry::VT_STACK_COUNT, stack_count, 1);
  }
  explicit WorldSpawnedItemEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldSpawnedItemEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldSpawnedItemEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldSpawnedItemEntry> CreateWorldSpawnedItemEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> item_id = 0,
    const ProtoType::Net::Vec3 *position = nullptr,
    int16_t stack_count = 1) {
  WorldSpawnedItemEntryBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_item_id(item_id);
  builder_.add_stack_count(stack_count);
  return builder_.Finish();
}

struct WorldSpawnedItemEntry::Traits {
  using type = WorldSpawnedItemEntry;
  static auto constexpr Create = CreateWorldSpawnedItemEntry;
};

inline ::flatbuffers::Offset<WorldSpawnedItemEntry> CreateWorldSpawnedItemEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *item_id = nullptr,
    const ProtoType::Net::Vec3 *position = nullptr,
    int16_t stack_count = 1) {
  auto item_id__ = item_id ? _fbb.CreateString(item_id) : 0;
  return ProtoType::Net::CreateWorldSpawnedItemEntry(
      _fbb,
      item_id__,
      position,
      stack_count);
}

::flatbuffers::Offset<WorldSpawnedItemEntry> CreateWorldSpawnedItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const WorldSpawnedItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_ItemSpawnRollT : public ::flatbuffers::NativeTable {
  typedef C2S_ItemSpawnRoll TableType;
  uint32_t spawn_point_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::WorldSpawnedItemEntryT>> items{};
  C2S_ItemSpawnRollT() = default;
  C2S_ItemSpawnRollT(const C2S_ItemSpawnRollT &o);
  C2S_ItemSpawnRollT(C2S_ItemSpawnRollT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_ItemSpawnRollT &operator=(C2S_ItemSpawnRollT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_ItemSpawnRoll FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_ItemSpawnRollT NativeTableType;
  typedef C2S_ItemSpawnRollBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPAWN_POINT_ID = 4,
    VT_ITEMS = 6
  };
  uint32_t spawn_point_id() const {
    return GetField<uint32_t>(VT_SPAWN_POINT_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SPAWN_POINT_ID, 4) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  C2S_ItemSpawnRollT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_ItemSpawnRollT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_ItemSpawnRoll> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemSpawnRollT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_ItemSpawnRollBuilder {
  typedef C2S_ItemSpawnRoll Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_spawn_point_id(uint32_t spawn_point_id) {
    fbb_.AddElement<uint32_t>(C2S_ItemSpawnRoll::VT_SPAWN_POINT_ID, spawn_point_id, 0);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>> items) {
    fbb_.AddOffset(C2S_ItemSpawnRoll::VT_ITEMS, items);
  }
  explicit C2S_ItemSpawnRollBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_ItemSpawnRoll> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_ItemSpawnRoll>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_ItemSpawnRoll> CreateC2S_ItemSpawnRoll(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t spawn_point_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>> items = 0) {
  C2S_ItemSpawnRollBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_spawn_point_id(spawn_point_id);
  return builder_.Finish();
}

struct C2S_ItemSpawnRoll::Traits {
  using type = C2S_ItemSpawnRoll;
  static auto constexpr Create = CreateC2S_ItemSpawnRoll;
};

inline ::flatbuffers::Offset<C2S_ItemSpawnRoll> CreateC2S_ItemSpawnRollDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t spawn_point_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateC2S_ItemSpawnRoll(
      _fbb,
      spawn_point_id,
      items__);
}

::flatbuffers::Offset<C2S_ItemSpawnRoll> CreateC2S_ItemSpawnRoll(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemSpawnRollT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_ItemSpawnStateT : public ::flatbuffers::NativeTable {
  typedef S2C_ItemSpawnState TableType;
  uint32_t spawn_point_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::WorldSpawnedItemEntryT>> items{};
  S2C_ItemSpawnStateT() = default;
  S2C_ItemSpawnStateT(const S2C_ItemSpawnStateT &o);
  S2C_ItemSpawnStateT(S2C_ItemSpawnStateT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_ItemSpawnStateT &operator=(S2C_ItemSpawnStateT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_ItemSpawnState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_ItemSpawnStateT NativeTableType;
  typedef S2C_ItemSpawnStateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPAWN_POINT_ID = 4,
    VT_ITEMS = 6
  };
  uint32_t spawn_point_id() const {
    return GetField<uint32_t>(VT_SPAWN_POINT_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *>(VT_ITEMS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SPAWN_POINT_ID, 4) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
  S2C_ItemSpawnStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_ItemSpawnStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_ItemSpawnState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemSpawnStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_ItemSpawnStateBuilder {
  typedef S2C_ItemSpawnState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_spawn_point_id(uint32_t spawn_point_id) {
    fbb_.AddElement<uint32_t>(S2C_ItemSpawnState::VT_SPAWN_POINT_ID, spawn_point_id, 0);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>> items) {
    fbb_.AddOffset(S2C_ItemSpawnState::VT_ITEMS, items);
  }
  explicit S2C_ItemSpawnStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_ItemSpawnState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_ItemSpawnState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_ItemSpawnState> CreateS2C_ItemSpawnState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t spawn_point_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>> items = 0) {
  S2C_ItemSpawnStateBuilder builder_(_fbb);
  builder_.add_items(items);
  builder_.add_spawn_point_id(spawn_point_id);
  return builder_.Finish();
}

struct S2C_ItemSpawnState::Traits {
  using type = S2C_ItemSpawnState;
  static auto constexpr Create = CreateS2C_ItemSpawnState;
};

inline ::flatbuffers::Offset<S2C_ItemSpawnState> CreateS2C_ItemSpawnStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t spawn_point_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>>(*items) : 0;
  return ProtoType::Net::CreateS2C_ItemSpawnState(
      _fbb,
      spawn_point_id,
      items__);
}

::flatbuffers::Offset<S2C_ItemSpawnState> CreateS2C_ItemSpawnState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemSpawnStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline C2S_ItemUseRequestT::C2S_ItemUseRequestT(const C2S_ItemUseRequestT &o)
      : header((o.header) ? new ProtoType::Net::Header(*o.header) : nullptr),
        item_instance_id(o.item_instance_id),
        slot(o.slot),
        use_type(o.use_type) {
}

inline C2S_ItemUseRequestT &C2S_ItemUseRequestT::operator=(C2S_ItemUseRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(header, o.header);
  std::swap(item_instance_id, o.item_instance_id);
  std::swap(slot, o.slot);
  std::swap(use_type, o.use_type);
  return *this;
}

inline C2S_ItemUseRequestT *C2S_ItemUseRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_ItemUseRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_ItemUseRequest::UnPackTo(C2S_ItemUseRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = header(); if (_e) _o->header = std::unique_ptr<ProtoType::Net::Header>(new ProtoType::Net::Header(*_e)); }
  { auto _e = item_instance_id(); _o->item_instance_id = _e; }
  { auto _e = slot(); _o->slot = _e; }
  { auto _e = use_type(); _o->use_type = _e; }
}

inline ::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_ItemUseRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_ItemUseRequest> C2S_ItemUseRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_ItemUseRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _header = _o->header ? _o->header.get() : nullptr;
  auto _item_instance_id = _o->item_instance_id;
  auto _slot = _o->slot;
  auto _use_type = _o->use_type;
  return ProtoType::Net::CreateC2S_ItemUseRequest(
      _fbb,
      _header,
      _item_instance_id,
      _slot,
      _use_type);
}

inline S2C_ItemUseResultT *S2C_ItemUseResult::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_ItemUseResultT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_ItemUseResult::UnPackTo(S2C_ItemUseResultT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = item_instance_id(); _o->item_instance_id = _e; }
  { auto _e = use_type(); _o->use_type = _e; }
  { auto _e = result(); _o->result = _e; }
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_ItemUseResult::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_ItemUseResult> S2C_ItemUseResult::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_ItemUseResultT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _item_instance_id = _o->item_instance_id;
  auto _use_type = _o->use_type;
  auto _result = _o->result;
  auto _value = _o->value;
  return ProtoType::Net::CreateS2C_ItemUseResult(
      _fbb,
      _player_id,
      _item_instance_id,
      _use_type,
      _result,
      _value);
}

inline S2C_ItemUseBroadcastT *S2C_ItemUseBroadcast::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_ItemUseBroadcastT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_ItemUseBroadcast::UnPackTo(S2C_ItemUseBroadcastT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = user_id(); _o->user_id = _e; }
  { auto _e = use_type(); _o->use_type = _e; }
  { auto _e = slot(); _o->slot = _e; }
}

inline ::flatbuffers::Offset<S2C_ItemUseBroadcast> CreateS2C_ItemUseBroadcast(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseBroadcastT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_ItemUseBroadcast::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_ItemUseBroadcast> S2C_ItemUseBroadcast::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseBroadcastT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_ItemUseBroadcastT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _user_id = _o->user_id;
  auto _use_type = _o->use_type;
  auto _slot = _o->slot;
  return ProtoType::Net::CreateS2C_ItemUseBroadcast(
      _fbb,
      _user_id,
      _use_type,
      _slot);
}

inline C2S_ContainerLootRollT::C2S_ContainerLootRollT(const C2S_ContainerLootRollT &o)
      : container_id(o.container_id) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::InventoryItemEntryT(*items_) : nullptr); }
}

inline C2S_ContainerLootRollT &C2S_ContainerLootRollT::operator=(C2S_ContainerLootRollT o) FLATBUFFERS_NOEXCEPT {
  std::swap(container_id, o.container_id);
  std::swap(items, o.items);
  return *this;
}

inline C2S_ContainerLootRollT *C2S_ContainerLootRoll::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_ContainerLootRollT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_ContainerLootRoll::UnPackTo(C2S_ContainerLootRollT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = container_id(); _o->container_id = _e; }
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::InventoryItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_ContainerLootRoll> CreateC2S_ContainerLootRoll(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ContainerLootRollT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_ContainerLootRoll::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_ContainerLootRoll> C2S_ContainerLootRoll::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ContainerLootRollT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_ContainerLootRollT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _container_id = _o->container_id;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateInventoryItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_ContainerLootRoll(
      _fbb,
      _container_id,
      _items);
}

inline S2C_ContainerLootStateT::S2C_ContainerLootStateT(const S2C_ContainerLootStateT &o)
      : container_id(o.container_id) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::InventoryItemEntryT(*items_) : nullptr); }
}

inline S2C_ContainerLootStateT &S2C_ContainerLootStateT::operator=(S2C_ContainerLootStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(container_id, o.container_id);
  std::swap(items, o.items);
  return *this;
}

inline S2C_ContainerLootStateT *S2C_ContainerLootState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_ContainerLootStateT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_ContainerLootState::UnPackTo(S2C_ContainerLootStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = container_id(); _o->container_id = _e; }
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::InventoryItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<S2C_ContainerLootState> CreateS2C_ContainerLootState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ContainerLootStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_ContainerLootState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_ContainerLootState> S2C_ContainerLootState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ContainerLootStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_ContainerLootStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _container_id = _o->container_id;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::InventoryItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateInventoryItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateS2C_ContainerLootState(
      _fbb,
      _container_id,
      _items);
}

inline WorldSpawnedItemEntryT::WorldSpawnedItemEntryT(const WorldSpawnedItemEntryT &o)
      : item_id(o.item_id),
        position((o.position) ? new ProtoType::Net::Vec3(*o.position) : nullptr),
        stack_count(o.stack_count) {
}

inline WorldSpawnedItemEntryT &WorldSpawnedItemEntryT::operator=(WorldSpawnedItemEntryT o) FLATBUFFERS_NOEXCEPT {
  std::swap(item_id, o.item_id);
  std::swap(position, o.position);
  std::swap(stack_count, o.stack_count);
  return *this;
}

inline WorldSpawnedItemEntryT *WorldSpawnedItemEntry::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<WorldSpawnedItemEntryT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void WorldSpawnedItemEntry::UnPackTo(WorldSpawnedItemEntryT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = item_id(); if (_e) _o->item_id = _e->str(); }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ProtoType::Net::Vec3>(new ProtoType::Net::Vec3(*_e)); }
  { auto _e = stack_count(); _o->stack_count = _e; }
}

inline ::flatbuffers::Offset<WorldSpawnedItemEntry> CreateWorldSpawnedItemEntry(::flatbuffers::FlatBufferBuilder &_fbb, const WorldSpawnedItemEntryT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return WorldSpawnedItemEntry::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<WorldSpawnedItemEntry> WorldSpawnedItemEntry::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const WorldSpawnedItemEntryT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const WorldSpawnedItemEntryT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _item_id = _o->item_id.empty() ? 0 : _fbb.CreateString(_o->item_id);
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _stack_count = _o->stack_count;
  return ProtoType::Net::CreateWorldSpawnedItemEntry(
      _fbb,
      _item_id,
      _position,
      _stack_count);
}

inline C2S_ItemSpawnRollT::C2S_ItemSpawnRollT(const C2S_ItemSpawnRollT &o)
      : spawn_point_id(o.spawn_point_id) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::WorldSpawnedItemEntryT(*items_) : nullptr); }
}

inline C2S_ItemSpawnRollT &C2S_ItemSpawnRollT::operator=(C2S_ItemSpawnRollT o) FLATBUFFERS_NOEXCEPT {
  std::swap(spawn_point_id, o.spawn_point_id);
  std::swap(items, o.items);
  return *this;
}

inline C2S_ItemSpawnRollT *C2S_ItemSpawnRoll::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_ItemSpawnRollT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_ItemSpawnRoll::UnPackTo(C2S_ItemSpawnRollT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = spawn_point_id(); _o->spawn_point_id = _e; }
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::WorldSpawnedItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<C2S_ItemSpawnRoll> CreateC2S_ItemSpawnRoll(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemSpawnRollT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_ItemSpawnRoll::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_ItemSpawnRoll> C2S_ItemSpawnRoll::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemSpawnRollT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_ItemSpawnRollT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _spawn_point_id = _o->spawn_point_id;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateWorldSpawnedItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateC2S_ItemSpawnRoll(
      _fbb,
      _spawn_point_id,
      _items);
}

inline S2C_ItemSpawnStateT::S2C_ItemSpawnStateT(const S2C_ItemSpawnStateT &o)
      : spawn_point_id(o.spawn_point_id) {
  items.reserve(o.items.size());
  for (const auto &items_ : o.items) { items.emplace_back((items_) ? new ProtoType::Net::WorldSpawnedItemEntryT(*items_) : nullptr); }
}

inline S2C_ItemSpawnStateT &S2C_ItemSpawnStateT::operator=(S2C_ItemSpawnStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(spawn_point_id, o.spawn_point_id);
  std::swap(items, o.items);
  return *this;
}

inline S2C_ItemSpawnStateT *S2C_ItemSpawnState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_ItemSpawnStateT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_ItemSpawnState::UnPackTo(S2C_ItemSpawnStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = spawn_point_id(); _o->spawn_point_id = _e; }
  { auto _e = items(); if (_e) { _o->items.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->items[_i]) { _e->Get(_i)->UnPackTo(_o->items[_i].get(), _resolver); } else { _o->items[_i] = std::unique_ptr<ProtoType::Net::WorldSpawnedItemEntryT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->items.resize(0); } }
}

inline ::flatbuffers::Offset<S2C_ItemSpawnState> CreateS2C_ItemSpawnState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemSpawnStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_ItemSpawnState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_ItemSpawnState> S2C_ItemSpawnState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemSpawnStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_ItemSpawnStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _spawn_point_id = _o->spawn_point_id;
  auto _items = _o->items.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::WorldSpawnedItemEntry>> (_o->items.size(), [](size_t i, _VectorArgs *__va) { return CreateWorldSpawnedItemEntry(*__va->__fbb, __va->__o->items[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateS2C_ItemSpawnState(
      _fbb,
      _spawn_point_id,
      _items);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_
