// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace ProtoType {
namespace Net {

struct C2S_ItemUseRequest;
struct C2S_ItemUseRequestBuilder;
struct C2S_ItemUseRequestT;

struct S2C_ItemUseResult;
struct S2C_ItemUseResultBuilder;
struct S2C_ItemUseResultT;

enum class ItemUseType : int8_t {
  Consume = 0,
  Equip = 1,
  Unequip = 2,
  Drop = 3,
  Reload = 4,
  Inspect = 5,
  ToggleAttachment = 6,
  MIN = Consume,
  MAX = ToggleAttachment
};

inline const ItemUseType (&EnumValuesItemUseType())[7] {
  static const ItemUseType values[] = {
    ItemUseType::Consume,
    ItemUseType::Equip,
    ItemUseType::Unequip,
    ItemUseType::Drop,
    ItemUseType::Reload,
    ItemUseType::Inspect,
    ItemUseType::ToggleAttachment
  };
  return values;
}

inline const char * const *EnumNamesItemUseType() {
  static const char * const names[8] = {
    "Consume",
    "Equip",
    "Unequip",
    "Drop",
    "Reload",
    "Inspect",
    "ToggleAttachment",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemUseType(ItemUseType e) {
  if (::flatbuffers::IsOutRange(e, ItemUseType::Consume, ItemUseType::ToggleAttachment)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemUseType()[index];
}

struct C2S_ItemUseRequestT : public ::flatbuffers::NativeTable {
  typedef C2S_ItemUseRequest TableType;
  std::unique_ptr<ProtoType::Net::Header> header{};
  uint64_t item_instance_id = 0;
  uint8_t slot = 0;
  ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume;
  C2S_ItemUseRequestT() = default;
  C2S_ItemUseRequestT(const C2S_ItemUseRequestT &o);
  C2S_ItemUseRequestT(C2S_ItemUseRequestT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_ItemUseRequestT &operator=(C2S_ItemUseRequestT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_ItemUseRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_ItemUseRequestT NativeTableType;
  typedef C2S_ItemUseRequestBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_ITEM_INSTANCE_ID = 6,
    VT_SLOT = 8,
    VT_USE_TYPE = 10
  };
  const ProtoType::Net::Header *header() const {
    return GetStruct<const ProtoType::Net::Header *>(VT_HEADER);
  }
  uint64_t item_instance_id() const {
    return GetField<uint64_t>(VT_ITEM_INSTANCE_ID, 0);
  }
  uint8_t slot() const {
    return GetField<uint8_t>(VT_SLOT, 0);
  }
  ProtoType::Net::ItemUseType use_type() const {
    return static_cast<ProtoType::Net::ItemUseType>(GetField<int8_t>(VT_USE_TYPE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ProtoType::Net::Header>(verifier, VT_HEADER, 4) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_INSTANCE_ID, 8) &&
           VerifyField<uint8_t>(verifier, VT_SLOT, 1) &&
           VerifyField<int8_t>(verifier, VT_USE_TYPE, 1) &&
           verifier.EndTable();
  }
  C2S_ItemUseRequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_ItemUseRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_ItemUseRequest> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_ItemUseRequestBuilder {
  typedef C2S_ItemUseRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(const ProtoType::Net::Header *header) {
    fbb_.AddStruct(C2S_ItemUseRequest::VT_HEADER, header);
  }
  void add_item_instance_id(uint64_t item_instance_id) {
    fbb_.AddElement<uint64_t>(C2S_ItemUseRequest::VT_ITEM_INSTANCE_ID, item_instance_id, 0);
  }
  void add_slot(uint8_t slot) {
    fbb_.AddElement<uint8_t>(C2S_ItemUseRequest::VT_SLOT, slot, 0);
  }
  void add_use_type(ProtoType::Net::ItemUseType use_type) {
    fbb_.AddElement<int8_t>(C2S_ItemUseRequest::VT_USE_TYPE, static_cast<int8_t>(use_type), 0);
  }
  explicit C2S_ItemUseRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_ItemUseRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_ItemUseRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ProtoType::Net::Header *header = nullptr,
    uint64_t item_instance_id = 0,
    uint8_t slot = 0,
    ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume) {
  C2S_ItemUseRequestBuilder builder_(_fbb);
  builder_.add_item_instance_id(item_instance_id);
  builder_.add_header(header);
  builder_.add_use_type(use_type);
  builder_.add_slot(slot);
  return builder_.Finish();
}

struct C2S_ItemUseRequest::Traits {
  using type = C2S_ItemUseRequest;
  static auto constexpr Create = CreateC2S_ItemUseRequest;
};

::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_ItemUseResultT : public ::flatbuffers::NativeTable {
  typedef S2C_ItemUseResult TableType;
  uint32_t player_id = 0;
  uint64_t item_instance_id = 0;
  ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume;
  ProtoType::Net::ResultCode result = ProtoType::Net::ResultCode::Ok;
  float value = 0.0f;
};

struct S2C_ItemUseResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_ItemUseResultT NativeTableType;
  typedef S2C_ItemUseResultBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_ITEM_INSTANCE_ID = 6,
    VT_USE_TYPE = 8,
    VT_RESULT = 10,
    VT_VALUE = 12
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint64_t item_instance_id() const {
    return GetField<uint64_t>(VT_ITEM_INSTANCE_ID, 0);
  }
  ProtoType::Net::ItemUseType use_type() const {
    return static_cast<ProtoType::Net::ItemUseType>(GetField<int8_t>(VT_USE_TYPE, 0));
  }
  ProtoType::Net::ResultCode result() const {
    return static_cast<ProtoType::Net::ResultCode>(GetField<int8_t>(VT_RESULT, 0));
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint64_t>(verifier, VT_ITEM_INSTANCE_ID, 8) &&
           VerifyField<int8_t>(verifier, VT_USE_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_RESULT, 1) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
  S2C_ItemUseResultT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_ItemUseResultT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_ItemUseResult> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_ItemUseResultBuilder {
  typedef S2C_ItemUseResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(S2C_ItemUseResult::VT_PLAYER_ID, player_id, 0);
  }
  void add_item_instance_id(uint64_t item_instance_id) {
    fbb_.AddElement<uint64_t>(S2C_ItemUseResult::VT_ITEM_INSTANCE_ID, item_instance_id, 0);
  }
  void add_use_type(ProtoType::Net::ItemUseType use_type) {
    fbb_.AddElement<int8_t>(S2C_ItemUseResult::VT_USE_TYPE, static_cast<int8_t>(use_type), 0);
  }
  void add_result(ProtoType::Net::ResultCode result) {
    fbb_.AddElement<int8_t>(S2C_ItemUseResult::VT_RESULT, static_cast<int8_t>(result), 0);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(S2C_ItemUseResult::VT_VALUE, value, 0.0f);
  }
  explicit S2C_ItemUseResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_ItemUseResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_ItemUseResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint64_t item_instance_id = 0,
    ProtoType::Net::ItemUseType use_type = ProtoType::Net::ItemUseType::Consume,
    ProtoType::Net::ResultCode result = ProtoType::Net::ResultCode::Ok,
    float value = 0.0f) {
  S2C_ItemUseResultBuilder builder_(_fbb);
  builder_.add_item_instance_id(item_instance_id);
  builder_.add_value(value);
  builder_.add_player_id(player_id);
  builder_.add_result(result);
  builder_.add_use_type(use_type);
  return builder_.Finish();
}

struct S2C_ItemUseResult::Traits {
  using type = S2C_ItemUseResult;
  static auto constexpr Create = CreateS2C_ItemUseResult;
};

::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline C2S_ItemUseRequestT::C2S_ItemUseRequestT(const C2S_ItemUseRequestT &o)
      : header((o.header) ? new ProtoType::Net::Header(*o.header) : nullptr),
        item_instance_id(o.item_instance_id),
        slot(o.slot),
        use_type(o.use_type) {
}

inline C2S_ItemUseRequestT &C2S_ItemUseRequestT::operator=(C2S_ItemUseRequestT o) FLATBUFFERS_NOEXCEPT {
  std::swap(header, o.header);
  std::swap(item_instance_id, o.item_instance_id);
  std::swap(slot, o.slot);
  std::swap(use_type, o.use_type);
  return *this;
}

inline C2S_ItemUseRequestT *C2S_ItemUseRequest::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_ItemUseRequestT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_ItemUseRequest::UnPackTo(C2S_ItemUseRequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = header(); if (_e) _o->header = std::unique_ptr<ProtoType::Net::Header>(new ProtoType::Net::Header(*_e)); }
  { auto _e = item_instance_id(); _o->item_instance_id = _e; }
  { auto _e = slot(); _o->slot = _e; }
  { auto _e = use_type(); _o->use_type = _e; }
}

inline ::flatbuffers::Offset<C2S_ItemUseRequest> CreateC2S_ItemUseRequest(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_ItemUseRequest::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_ItemUseRequest> C2S_ItemUseRequest::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_ItemUseRequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_ItemUseRequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _header = _o->header ? _o->header.get() : nullptr;
  auto _item_instance_id = _o->item_instance_id;
  auto _slot = _o->slot;
  auto _use_type = _o->use_type;
  return ProtoType::Net::CreateC2S_ItemUseRequest(
      _fbb,
      _header,
      _item_instance_id,
      _slot,
      _use_type);
}

inline S2C_ItemUseResultT *S2C_ItemUseResult::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_ItemUseResultT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_ItemUseResult::UnPackTo(S2C_ItemUseResultT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = item_instance_id(); _o->item_instance_id = _e; }
  { auto _e = use_type(); _o->use_type = _e; }
  { auto _e = result(); _o->result = _e; }
  { auto _e = value(); _o->value = _e; }
}

inline ::flatbuffers::Offset<S2C_ItemUseResult> CreateS2C_ItemUseResult(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_ItemUseResult::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_ItemUseResult> S2C_ItemUseResult::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_ItemUseResultT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_ItemUseResultT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _item_instance_id = _o->item_instance_id;
  auto _use_type = _o->use_type;
  auto _result = _o->result;
  auto _value = _o->value;
  return ProtoType::Net::CreateS2C_ItemUseResult(
      _fbb,
      _player_id,
      _item_instance_id,
      _use_type,
      _result,
      _value);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_ITEM_PROTOTYPE_NET_H_
