// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATCH_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_MATCH_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace ProtoType {
namespace Net {

struct C2S_RequestMatch;
struct C2S_RequestMatchBuilder;
struct C2S_RequestMatchT;

struct S2C_MatchTicket;
struct S2C_MatchTicketBuilder;
struct S2C_MatchTicketT;

struct C2S_JoinMatch;
struct C2S_JoinMatchBuilder;
struct C2S_JoinMatchT;

struct S2C_JoinMatchFail;
struct S2C_JoinMatchFailBuilder;
struct S2C_JoinMatchFailT;

enum class JoinMatchFailReason : int8_t {
  InvalidOrExpiredTicket = 0,
  MIN = InvalidOrExpiredTicket,
  MAX = InvalidOrExpiredTicket
};

inline const JoinMatchFailReason (&EnumValuesJoinMatchFailReason())[1] {
  static const JoinMatchFailReason values[] = {
    JoinMatchFailReason::InvalidOrExpiredTicket
  };
  return values;
}

inline const char * const *EnumNamesJoinMatchFailReason() {
  static const char * const names[2] = {
    "InvalidOrExpiredTicket",
    nullptr
  };
  return names;
}

inline const char *EnumNameJoinMatchFailReason(JoinMatchFailReason e) {
  if (::flatbuffers::IsOutRange(e, JoinMatchFailReason::InvalidOrExpiredTicket, JoinMatchFailReason::InvalidOrExpiredTicket)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesJoinMatchFailReason()[index];
}

struct C2S_RequestMatchT : public ::flatbuffers::NativeTable {
  typedef C2S_RequestMatch TableType;
};

struct C2S_RequestMatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_RequestMatchT NativeTableType;
  typedef C2S_RequestMatchBuilder Builder;
  struct Traits;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  C2S_RequestMatchT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_RequestMatchT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_RequestMatch> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestMatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_RequestMatchBuilder {
  typedef C2S_RequestMatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit C2S_RequestMatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_RequestMatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_RequestMatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_RequestMatch> CreateC2S_RequestMatch(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  C2S_RequestMatchBuilder builder_(_fbb);
  return builder_.Finish();
}

struct C2S_RequestMatch::Traits {
  using type = C2S_RequestMatch;
  static auto constexpr Create = CreateC2S_RequestMatch;
};

::flatbuffers::Offset<C2S_RequestMatch> CreateC2S_RequestMatch(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestMatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_MatchTicketT : public ::flatbuffers::NativeTable {
  typedef S2C_MatchTicket TableType;
  std::string game_server_host{};
  uint16_t game_server_port = 0;
  std::string ticket{};
  uint64_t expires_at_unix_ms = 0;
};

struct S2C_MatchTicket FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_MatchTicketT NativeTableType;
  typedef S2C_MatchTicketBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAME_SERVER_HOST = 4,
    VT_GAME_SERVER_PORT = 6,
    VT_TICKET = 8,
    VT_EXPIRES_AT_UNIX_MS = 10
  };
  const ::flatbuffers::String *game_server_host() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GAME_SERVER_HOST);
  }
  uint16_t game_server_port() const {
    return GetField<uint16_t>(VT_GAME_SERVER_PORT, 0);
  }
  const ::flatbuffers::String *ticket() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TICKET);
  }
  uint64_t expires_at_unix_ms() const {
    return GetField<uint64_t>(VT_EXPIRES_AT_UNIX_MS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GAME_SERVER_HOST) &&
           verifier.VerifyString(game_server_host()) &&
           VerifyField<uint16_t>(verifier, VT_GAME_SERVER_PORT, 2) &&
           VerifyOffset(verifier, VT_TICKET) &&
           verifier.VerifyString(ticket()) &&
           VerifyField<uint64_t>(verifier, VT_EXPIRES_AT_UNIX_MS, 8) &&
           verifier.EndTable();
  }
  S2C_MatchTicketT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_MatchTicketT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_MatchTicket> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MatchTicketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_MatchTicketBuilder {
  typedef S2C_MatchTicket Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_game_server_host(::flatbuffers::Offset<::flatbuffers::String> game_server_host) {
    fbb_.AddOffset(S2C_MatchTicket::VT_GAME_SERVER_HOST, game_server_host);
  }
  void add_game_server_port(uint16_t game_server_port) {
    fbb_.AddElement<uint16_t>(S2C_MatchTicket::VT_GAME_SERVER_PORT, game_server_port, 0);
  }
  void add_ticket(::flatbuffers::Offset<::flatbuffers::String> ticket) {
    fbb_.AddOffset(S2C_MatchTicket::VT_TICKET, ticket);
  }
  void add_expires_at_unix_ms(uint64_t expires_at_unix_ms) {
    fbb_.AddElement<uint64_t>(S2C_MatchTicket::VT_EXPIRES_AT_UNIX_MS, expires_at_unix_ms, 0);
  }
  explicit S2C_MatchTicketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_MatchTicket> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_MatchTicket>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_MatchTicket> CreateS2C_MatchTicket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> game_server_host = 0,
    uint16_t game_server_port = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ticket = 0,
    uint64_t expires_at_unix_ms = 0) {
  S2C_MatchTicketBuilder builder_(_fbb);
  builder_.add_expires_at_unix_ms(expires_at_unix_ms);
  builder_.add_ticket(ticket);
  builder_.add_game_server_host(game_server_host);
  builder_.add_game_server_port(game_server_port);
  return builder_.Finish();
}

struct S2C_MatchTicket::Traits {
  using type = S2C_MatchTicket;
  static auto constexpr Create = CreateS2C_MatchTicket;
};

inline ::flatbuffers::Offset<S2C_MatchTicket> CreateS2C_MatchTicketDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *game_server_host = nullptr,
    uint16_t game_server_port = 0,
    const char *ticket = nullptr,
    uint64_t expires_at_unix_ms = 0) {
  auto game_server_host__ = game_server_host ? _fbb.CreateString(game_server_host) : 0;
  auto ticket__ = ticket ? _fbb.CreateString(ticket) : 0;
  return ProtoType::Net::CreateS2C_MatchTicket(
      _fbb,
      game_server_host__,
      game_server_port,
      ticket__,
      expires_at_unix_ms);
}

::flatbuffers::Offset<S2C_MatchTicket> CreateS2C_MatchTicket(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MatchTicketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct C2S_JoinMatchT : public ::flatbuffers::NativeTable {
  typedef C2S_JoinMatch TableType;
  std::string ticket{};
};

struct C2S_JoinMatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_JoinMatchT NativeTableType;
  typedef C2S_JoinMatchBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICKET = 4
  };
  const ::flatbuffers::String *ticket() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TICKET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TICKET) &&
           verifier.VerifyString(ticket()) &&
           verifier.EndTable();
  }
  C2S_JoinMatchT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_JoinMatchT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_JoinMatch> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_JoinMatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_JoinMatchBuilder {
  typedef C2S_JoinMatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ticket(::flatbuffers::Offset<::flatbuffers::String> ticket) {
    fbb_.AddOffset(C2S_JoinMatch::VT_TICKET, ticket);
  }
  explicit C2S_JoinMatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_JoinMatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_JoinMatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_JoinMatch> CreateC2S_JoinMatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ticket = 0) {
  C2S_JoinMatchBuilder builder_(_fbb);
  builder_.add_ticket(ticket);
  return builder_.Finish();
}

struct C2S_JoinMatch::Traits {
  using type = C2S_JoinMatch;
  static auto constexpr Create = CreateC2S_JoinMatch;
};

inline ::flatbuffers::Offset<C2S_JoinMatch> CreateC2S_JoinMatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ticket = nullptr) {
  auto ticket__ = ticket ? _fbb.CreateString(ticket) : 0;
  return ProtoType::Net::CreateC2S_JoinMatch(
      _fbb,
      ticket__);
}

::flatbuffers::Offset<C2S_JoinMatch> CreateC2S_JoinMatch(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_JoinMatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_JoinMatchFailT : public ::flatbuffers::NativeTable {
  typedef S2C_JoinMatchFail TableType;
  ProtoType::Net::JoinMatchFailReason reason = ProtoType::Net::JoinMatchFailReason::InvalidOrExpiredTicket;
};

struct S2C_JoinMatchFail FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_JoinMatchFailT NativeTableType;
  typedef S2C_JoinMatchFailBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4
  };
  ProtoType::Net::JoinMatchFailReason reason() const {
    return static_cast<ProtoType::Net::JoinMatchFailReason>(GetField<int8_t>(VT_REASON, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_REASON, 1) &&
           verifier.EndTable();
  }
  S2C_JoinMatchFailT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_JoinMatchFailT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_JoinMatchFail> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_JoinMatchFailT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_JoinMatchFailBuilder {
  typedef S2C_JoinMatchFail Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(ProtoType::Net::JoinMatchFailReason reason) {
    fbb_.AddElement<int8_t>(S2C_JoinMatchFail::VT_REASON, static_cast<int8_t>(reason), 0);
  }
  explicit S2C_JoinMatchFailBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_JoinMatchFail> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_JoinMatchFail>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_JoinMatchFail> CreateS2C_JoinMatchFail(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ProtoType::Net::JoinMatchFailReason reason = ProtoType::Net::JoinMatchFailReason::InvalidOrExpiredTicket) {
  S2C_JoinMatchFailBuilder builder_(_fbb);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct S2C_JoinMatchFail::Traits {
  using type = S2C_JoinMatchFail;
  static auto constexpr Create = CreateS2C_JoinMatchFail;
};

::flatbuffers::Offset<S2C_JoinMatchFail> CreateS2C_JoinMatchFail(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_JoinMatchFailT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline C2S_RequestMatchT *C2S_RequestMatch::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_RequestMatchT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_RequestMatch::UnPackTo(C2S_RequestMatchT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<C2S_RequestMatch> CreateC2S_RequestMatch(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestMatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_RequestMatch::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_RequestMatch> C2S_RequestMatch::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_RequestMatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_RequestMatchT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return ProtoType::Net::CreateC2S_RequestMatch(
      _fbb);
}

inline S2C_MatchTicketT *S2C_MatchTicket::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_MatchTicketT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_MatchTicket::UnPackTo(S2C_MatchTicketT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = game_server_host(); if (_e) _o->game_server_host = _e->str(); }
  { auto _e = game_server_port(); _o->game_server_port = _e; }
  { auto _e = ticket(); if (_e) _o->ticket = _e->str(); }
  { auto _e = expires_at_unix_ms(); _o->expires_at_unix_ms = _e; }
}

inline ::flatbuffers::Offset<S2C_MatchTicket> CreateS2C_MatchTicket(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MatchTicketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_MatchTicket::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_MatchTicket> S2C_MatchTicket::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MatchTicketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_MatchTicketT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _game_server_host = _o->game_server_host.empty() ? 0 : _fbb.CreateString(_o->game_server_host);
  auto _game_server_port = _o->game_server_port;
  auto _ticket = _o->ticket.empty() ? 0 : _fbb.CreateString(_o->ticket);
  auto _expires_at_unix_ms = _o->expires_at_unix_ms;
  return ProtoType::Net::CreateS2C_MatchTicket(
      _fbb,
      _game_server_host,
      _game_server_port,
      _ticket,
      _expires_at_unix_ms);
}

inline C2S_JoinMatchT *C2S_JoinMatch::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_JoinMatchT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_JoinMatch::UnPackTo(C2S_JoinMatchT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = ticket(); if (_e) _o->ticket = _e->str(); }
}

inline ::flatbuffers::Offset<C2S_JoinMatch> CreateC2S_JoinMatch(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_JoinMatchT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_JoinMatch::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_JoinMatch> C2S_JoinMatch::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_JoinMatchT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_JoinMatchT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _ticket = _o->ticket.empty() ? 0 : _fbb.CreateString(_o->ticket);
  return ProtoType::Net::CreateC2S_JoinMatch(
      _fbb,
      _ticket);
}

inline S2C_JoinMatchFailT *S2C_JoinMatchFail::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_JoinMatchFailT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_JoinMatchFail::UnPackTo(S2C_JoinMatchFailT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = reason(); _o->reason = _e; }
}

inline ::flatbuffers::Offset<S2C_JoinMatchFail> CreateS2C_JoinMatchFail(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_JoinMatchFailT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_JoinMatchFail::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_JoinMatchFail> S2C_JoinMatchFail::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_JoinMatchFailT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_JoinMatchFailT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _reason = _o->reason;
  return ProtoType::Net::CreateS2C_JoinMatchFail(
      _fbb,
      _reason);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_MATCH_PROTOTYPE_NET_H_
