// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MOVEMENT_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_MOVEMENT_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace ProtoType {
namespace Net {

struct C2S_MoveInput;
struct C2S_MoveInputBuilder;
struct C2S_MoveInputT;

struct S2C_MoveState;
struct S2C_MoveStateBuilder;
struct S2C_MoveStateT;

enum class MoveFlags : uint16_t {
  Sprint = 1,
  Crouch = 2,
  Prone = 4,
  Jump = 8,
  ADS = 16,
  Falling = 32,
  Swimming = 64,
  Leaning_Left = 128,
  Leaning_Right = 256,
  NONE = 0,
  ANY = 511
};
FLATBUFFERS_DEFINE_BITMASK_OPERATORS(MoveFlags, uint16_t)

inline const MoveFlags (&EnumValuesMoveFlags())[9] {
  static const MoveFlags values[] = {
    MoveFlags::Sprint,
    MoveFlags::Crouch,
    MoveFlags::Prone,
    MoveFlags::Jump,
    MoveFlags::ADS,
    MoveFlags::Falling,
    MoveFlags::Swimming,
    MoveFlags::Leaning_Left,
    MoveFlags::Leaning_Right
  };
  return values;
}

inline const char *EnumNameMoveFlags(MoveFlags e) {
  switch (e) {
    case MoveFlags::Sprint: return "Sprint";
    case MoveFlags::Crouch: return "Crouch";
    case MoveFlags::Prone: return "Prone";
    case MoveFlags::Jump: return "Jump";
    case MoveFlags::ADS: return "ADS";
    case MoveFlags::Falling: return "Falling";
    case MoveFlags::Swimming: return "Swimming";
    case MoveFlags::Leaning_Left: return "Leaning_Left";
    case MoveFlags::Leaning_Right: return "Leaning_Right";
    default: return "";
  }
}

struct C2S_MoveInputT : public ::flatbuffers::NativeTable {
  typedef C2S_MoveInput TableType;
  std::unique_ptr<ProtoType::Net::Header> header{};
  std::unique_ptr<ProtoType::Net::Vec2> move_input{};
  std::unique_ptr<ProtoType::Net::Rotator> look{};
  ProtoType::Net::MoveFlags flags = static_cast<ProtoType::Net::MoveFlags>(0);
  C2S_MoveInputT() = default;
  C2S_MoveInputT(const C2S_MoveInputT &o);
  C2S_MoveInputT(C2S_MoveInputT&&) FLATBUFFERS_NOEXCEPT = default;
  C2S_MoveInputT &operator=(C2S_MoveInputT o) FLATBUFFERS_NOEXCEPT;
};

struct C2S_MoveInput FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_MoveInputT NativeTableType;
  typedef C2S_MoveInputBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_MOVE_INPUT = 6,
    VT_LOOK = 8,
    VT_FLAGS = 10
  };
  const ProtoType::Net::Header *header() const {
    return GetStruct<const ProtoType::Net::Header *>(VT_HEADER);
  }
  const ProtoType::Net::Vec2 *move_input() const {
    return GetStruct<const ProtoType::Net::Vec2 *>(VT_MOVE_INPUT);
  }
  const ProtoType::Net::Rotator *look() const {
    return GetStruct<const ProtoType::Net::Rotator *>(VT_LOOK);
  }
  ProtoType::Net::MoveFlags flags() const {
    return static_cast<ProtoType::Net::MoveFlags>(GetField<uint16_t>(VT_FLAGS, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<ProtoType::Net::Header>(verifier, VT_HEADER, 4) &&
           VerifyField<ProtoType::Net::Vec2>(verifier, VT_MOVE_INPUT, 4) &&
           VerifyField<ProtoType::Net::Rotator>(verifier, VT_LOOK, 4) &&
           VerifyField<uint16_t>(verifier, VT_FLAGS, 2) &&
           verifier.EndTable();
  }
  C2S_MoveInputT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_MoveInputT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_MoveInput> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_MoveInputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_MoveInputBuilder {
  typedef C2S_MoveInput Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(const ProtoType::Net::Header *header) {
    fbb_.AddStruct(C2S_MoveInput::VT_HEADER, header);
  }
  void add_move_input(const ProtoType::Net::Vec2 *move_input) {
    fbb_.AddStruct(C2S_MoveInput::VT_MOVE_INPUT, move_input);
  }
  void add_look(const ProtoType::Net::Rotator *look) {
    fbb_.AddStruct(C2S_MoveInput::VT_LOOK, look);
  }
  void add_flags(ProtoType::Net::MoveFlags flags) {
    fbb_.AddElement<uint16_t>(C2S_MoveInput::VT_FLAGS, static_cast<uint16_t>(flags), 0);
  }
  explicit C2S_MoveInputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_MoveInput> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_MoveInput>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_MoveInput> CreateC2S_MoveInput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ProtoType::Net::Header *header = nullptr,
    const ProtoType::Net::Vec2 *move_input = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    ProtoType::Net::MoveFlags flags = static_cast<ProtoType::Net::MoveFlags>(0)) {
  C2S_MoveInputBuilder builder_(_fbb);
  builder_.add_look(look);
  builder_.add_move_input(move_input);
  builder_.add_header(header);
  builder_.add_flags(flags);
  return builder_.Finish();
}

struct C2S_MoveInput::Traits {
  using type = C2S_MoveInput;
  static auto constexpr Create = CreateC2S_MoveInput;
};

::flatbuffers::Offset<C2S_MoveInput> CreateC2S_MoveInput(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_MoveInputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_MoveStateT : public ::flatbuffers::NativeTable {
  typedef S2C_MoveState TableType;
  uint32_t player_id = 0;
  uint32_t server_tick = 0;
  std::unique_ptr<ProtoType::Net::Vec3> position{};
  std::unique_ptr<ProtoType::Net::Vec3> velocity{};
  std::unique_ptr<ProtoType::Net::Rotator> look{};
  ProtoType::Net::MoveFlags flags = static_cast<ProtoType::Net::MoveFlags>(0);
  uint32_t ack_client_seq = 0;
  S2C_MoveStateT() = default;
  S2C_MoveStateT(const S2C_MoveStateT &o);
  S2C_MoveStateT(S2C_MoveStateT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_MoveStateT &operator=(S2C_MoveStateT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_MoveState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_MoveStateT NativeTableType;
  typedef S2C_MoveStateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_SERVER_TICK = 6,
    VT_POSITION = 8,
    VT_VELOCITY = 10,
    VT_LOOK = 12,
    VT_FLAGS = 14,
    VT_ACK_CLIENT_SEQ = 16
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint32_t server_tick() const {
    return GetField<uint32_t>(VT_SERVER_TICK, 0);
  }
  const ProtoType::Net::Vec3 *position() const {
    return GetStruct<const ProtoType::Net::Vec3 *>(VT_POSITION);
  }
  const ProtoType::Net::Vec3 *velocity() const {
    return GetStruct<const ProtoType::Net::Vec3 *>(VT_VELOCITY);
  }
  const ProtoType::Net::Rotator *look() const {
    return GetStruct<const ProtoType::Net::Rotator *>(VT_LOOK);
  }
  ProtoType::Net::MoveFlags flags() const {
    return static_cast<ProtoType::Net::MoveFlags>(GetField<uint16_t>(VT_FLAGS, 0));
  }
  uint32_t ack_client_seq() const {
    return GetField<uint32_t>(VT_ACK_CLIENT_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SERVER_TICK, 4) &&
           VerifyField<ProtoType::Net::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<ProtoType::Net::Vec3>(verifier, VT_VELOCITY, 4) &&
           VerifyField<ProtoType::Net::Rotator>(verifier, VT_LOOK, 4) &&
           VerifyField<uint16_t>(verifier, VT_FLAGS, 2) &&
           VerifyField<uint32_t>(verifier, VT_ACK_CLIENT_SEQ, 4) &&
           verifier.EndTable();
  }
  S2C_MoveStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_MoveStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_MoveState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MoveStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_MoveStateBuilder {
  typedef S2C_MoveState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(S2C_MoveState::VT_PLAYER_ID, player_id, 0);
  }
  void add_server_tick(uint32_t server_tick) {
    fbb_.AddElement<uint32_t>(S2C_MoveState::VT_SERVER_TICK, server_tick, 0);
  }
  void add_position(const ProtoType::Net::Vec3 *position) {
    fbb_.AddStruct(S2C_MoveState::VT_POSITION, position);
  }
  void add_velocity(const ProtoType::Net::Vec3 *velocity) {
    fbb_.AddStruct(S2C_MoveState::VT_VELOCITY, velocity);
  }
  void add_look(const ProtoType::Net::Rotator *look) {
    fbb_.AddStruct(S2C_MoveState::VT_LOOK, look);
  }
  void add_flags(ProtoType::Net::MoveFlags flags) {
    fbb_.AddElement<uint16_t>(S2C_MoveState::VT_FLAGS, static_cast<uint16_t>(flags), 0);
  }
  void add_ack_client_seq(uint32_t ack_client_seq) {
    fbb_.AddElement<uint32_t>(S2C_MoveState::VT_ACK_CLIENT_SEQ, ack_client_seq, 0);
  }
  explicit S2C_MoveStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_MoveState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_MoveState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_MoveState> CreateS2C_MoveState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint32_t server_tick = 0,
    const ProtoType::Net::Vec3 *position = nullptr,
    const ProtoType::Net::Vec3 *velocity = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    ProtoType::Net::MoveFlags flags = static_cast<ProtoType::Net::MoveFlags>(0),
    uint32_t ack_client_seq = 0) {
  S2C_MoveStateBuilder builder_(_fbb);
  builder_.add_ack_client_seq(ack_client_seq);
  builder_.add_look(look);
  builder_.add_velocity(velocity);
  builder_.add_position(position);
  builder_.add_server_tick(server_tick);
  builder_.add_player_id(player_id);
  builder_.add_flags(flags);
  return builder_.Finish();
}

struct S2C_MoveState::Traits {
  using type = S2C_MoveState;
  static auto constexpr Create = CreateS2C_MoveState;
};

::flatbuffers::Offset<S2C_MoveState> CreateS2C_MoveState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MoveStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline C2S_MoveInputT::C2S_MoveInputT(const C2S_MoveInputT &o)
      : header((o.header) ? new ProtoType::Net::Header(*o.header) : nullptr),
        move_input((o.move_input) ? new ProtoType::Net::Vec2(*o.move_input) : nullptr),
        look((o.look) ? new ProtoType::Net::Rotator(*o.look) : nullptr),
        flags(o.flags) {
}

inline C2S_MoveInputT &C2S_MoveInputT::operator=(C2S_MoveInputT o) FLATBUFFERS_NOEXCEPT {
  std::swap(header, o.header);
  std::swap(move_input, o.move_input);
  std::swap(look, o.look);
  std::swap(flags, o.flags);
  return *this;
}

inline C2S_MoveInputT *C2S_MoveInput::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_MoveInputT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_MoveInput::UnPackTo(C2S_MoveInputT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = header(); if (_e) _o->header = std::unique_ptr<ProtoType::Net::Header>(new ProtoType::Net::Header(*_e)); }
  { auto _e = move_input(); if (_e) _o->move_input = std::unique_ptr<ProtoType::Net::Vec2>(new ProtoType::Net::Vec2(*_e)); }
  { auto _e = look(); if (_e) _o->look = std::unique_ptr<ProtoType::Net::Rotator>(new ProtoType::Net::Rotator(*_e)); }
  { auto _e = flags(); _o->flags = _e; }
}

inline ::flatbuffers::Offset<C2S_MoveInput> CreateC2S_MoveInput(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_MoveInputT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_MoveInput::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_MoveInput> C2S_MoveInput::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_MoveInputT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_MoveInputT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _header = _o->header ? _o->header.get() : nullptr;
  auto _move_input = _o->move_input ? _o->move_input.get() : nullptr;
  auto _look = _o->look ? _o->look.get() : nullptr;
  auto _flags = _o->flags;
  return ProtoType::Net::CreateC2S_MoveInput(
      _fbb,
      _header,
      _move_input,
      _look,
      _flags);
}

inline S2C_MoveStateT::S2C_MoveStateT(const S2C_MoveStateT &o)
      : player_id(o.player_id),
        server_tick(o.server_tick),
        position((o.position) ? new ProtoType::Net::Vec3(*o.position) : nullptr),
        velocity((o.velocity) ? new ProtoType::Net::Vec3(*o.velocity) : nullptr),
        look((o.look) ? new ProtoType::Net::Rotator(*o.look) : nullptr),
        flags(o.flags),
        ack_client_seq(o.ack_client_seq) {
}

inline S2C_MoveStateT &S2C_MoveStateT::operator=(S2C_MoveStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(player_id, o.player_id);
  std::swap(server_tick, o.server_tick);
  std::swap(position, o.position);
  std::swap(velocity, o.velocity);
  std::swap(look, o.look);
  std::swap(flags, o.flags);
  std::swap(ack_client_seq, o.ack_client_seq);
  return *this;
}

inline S2C_MoveStateT *S2C_MoveState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_MoveStateT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_MoveState::UnPackTo(S2C_MoveStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = server_tick(); _o->server_tick = _e; }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ProtoType::Net::Vec3>(new ProtoType::Net::Vec3(*_e)); }
  { auto _e = velocity(); if (_e) _o->velocity = std::unique_ptr<ProtoType::Net::Vec3>(new ProtoType::Net::Vec3(*_e)); }
  { auto _e = look(); if (_e) _o->look = std::unique_ptr<ProtoType::Net::Rotator>(new ProtoType::Net::Rotator(*_e)); }
  { auto _e = flags(); _o->flags = _e; }
  { auto _e = ack_client_seq(); _o->ack_client_seq = _e; }
}

inline ::flatbuffers::Offset<S2C_MoveState> CreateS2C_MoveState(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MoveStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_MoveState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_MoveState> S2C_MoveState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_MoveStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_MoveStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _server_tick = _o->server_tick;
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _velocity = _o->velocity ? _o->velocity.get() : nullptr;
  auto _look = _o->look ? _o->look.get() : nullptr;
  auto _flags = _o->flags;
  auto _ack_client_seq = _o->ack_client_seq;
  return ProtoType::Net::CreateS2C_MoveState(
      _fbb,
      _player_id,
      _server_tick,
      _position,
      _velocity,
      _look,
      _flags,
      _ack_client_seq);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_MOVEMENT_PROTOTYPE_NET_H_
