// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYER_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_PLAYER_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "common.h"

namespace ProtoType {
namespace Net {

struct EquippedVisual;
struct EquippedVisualBuilder;
struct EquippedVisualT;

struct S2C_SendAvatarInfo;
struct S2C_SendAvatarInfoBuilder;
struct S2C_SendAvatarInfoT;

struct S2C_SendPlayerInfo;
struct S2C_SendPlayerInfoBuilder;
struct S2C_SendPlayerInfoT;

enum class EquipSlot : int8_t {
  Head = 0,
  Chest = 1,
  Back = 2,
  Hands = 3,
  Legs = 4,
  Feet = 5,
  PrimaryWeapon = 6,
  SecondaryWeapon = 7,
  Melee = 8,
  MIN = Head,
  MAX = Melee
};

inline const EquipSlot (&EnumValuesEquipSlot())[9] {
  static const EquipSlot values[] = {
    EquipSlot::Head,
    EquipSlot::Chest,
    EquipSlot::Back,
    EquipSlot::Hands,
    EquipSlot::Legs,
    EquipSlot::Feet,
    EquipSlot::PrimaryWeapon,
    EquipSlot::SecondaryWeapon,
    EquipSlot::Melee
  };
  return values;
}

inline const char * const *EnumNamesEquipSlot() {
  static const char * const names[10] = {
    "Head",
    "Chest",
    "Back",
    "Hands",
    "Legs",
    "Feet",
    "PrimaryWeapon",
    "SecondaryWeapon",
    "Melee",
    nullptr
  };
  return names;
}

inline const char *EnumNameEquipSlot(EquipSlot e) {
  if (::flatbuffers::IsOutRange(e, EquipSlot::Head, EquipSlot::Melee)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEquipSlot()[index];
}

struct EquippedVisualT : public ::flatbuffers::NativeTable {
  typedef EquippedVisual TableType;
  ProtoType::Net::EquipSlot slot = ProtoType::Net::EquipSlot::Head;
  uint32_t item_id = 0;
};

struct EquippedVisual FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EquippedVisualT NativeTableType;
  typedef EquippedVisualBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SLOT = 4,
    VT_ITEM_ID = 6
  };
  ProtoType::Net::EquipSlot slot() const {
    return static_cast<ProtoType::Net::EquipSlot>(GetField<int8_t>(VT_SLOT, 0));
  }
  uint32_t item_id() const {
    return GetField<uint32_t>(VT_ITEM_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SLOT, 1) &&
           VerifyField<uint32_t>(verifier, VT_ITEM_ID, 4) &&
           verifier.EndTable();
  }
  EquippedVisualT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EquippedVisualT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EquippedVisual> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EquippedVisualT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EquippedVisualBuilder {
  typedef EquippedVisual Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_slot(ProtoType::Net::EquipSlot slot) {
    fbb_.AddElement<int8_t>(EquippedVisual::VT_SLOT, static_cast<int8_t>(slot), 0);
  }
  void add_item_id(uint32_t item_id) {
    fbb_.AddElement<uint32_t>(EquippedVisual::VT_ITEM_ID, item_id, 0);
  }
  explicit EquippedVisualBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EquippedVisual> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EquippedVisual>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EquippedVisual> CreateEquippedVisual(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ProtoType::Net::EquipSlot slot = ProtoType::Net::EquipSlot::Head,
    uint32_t item_id = 0) {
  EquippedVisualBuilder builder_(_fbb);
  builder_.add_item_id(item_id);
  builder_.add_slot(slot);
  return builder_.Finish();
}

struct EquippedVisual::Traits {
  using type = EquippedVisual;
  static auto constexpr Create = CreateEquippedVisual;
};

::flatbuffers::Offset<EquippedVisual> CreateEquippedVisual(::flatbuffers::FlatBufferBuilder &_fbb, const EquippedVisualT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_SendAvatarInfoT : public ::flatbuffers::NativeTable {
  typedef S2C_SendAvatarInfo TableType;
  uint32_t player_id = 0;
  std::string nickname{};
  std::unique_ptr<ProtoType::Net::Vec3> position{};
  std::unique_ptr<ProtoType::Net::Rotator> look{};
  float health = 0.0f;
  float max_health = 0.0f;
  uint32_t level = 0;
  uint32_t character_model_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::EquippedVisualT>> equipped{};
  S2C_SendAvatarInfoT() = default;
  S2C_SendAvatarInfoT(const S2C_SendAvatarInfoT &o);
  S2C_SendAvatarInfoT(S2C_SendAvatarInfoT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_SendAvatarInfoT &operator=(S2C_SendAvatarInfoT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_SendAvatarInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_SendAvatarInfoT NativeTableType;
  typedef S2C_SendAvatarInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_NICKNAME = 6,
    VT_POSITION = 8,
    VT_LOOK = 10,
    VT_HEALTH = 12,
    VT_MAX_HEALTH = 14,
    VT_LEVEL = 16,
    VT_CHARACTER_MODEL_ID = 18,
    VT_EQUIPPED = 20
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  const ::flatbuffers::String *nickname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NICKNAME);
  }
  const ProtoType::Net::Vec3 *position() const {
    return GetStruct<const ProtoType::Net::Vec3 *>(VT_POSITION);
  }
  const ProtoType::Net::Rotator *look() const {
    return GetStruct<const ProtoType::Net::Rotator *>(VT_LOOK);
  }
  float health() const {
    return GetField<float>(VT_HEALTH, 0.0f);
  }
  float max_health() const {
    return GetField<float>(VT_MAX_HEALTH, 0.0f);
  }
  uint32_t level() const {
    return GetField<uint32_t>(VT_LEVEL, 0);
  }
  uint32_t character_model_id() const {
    return GetField<uint32_t>(VT_CHARACTER_MODEL_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *equipped() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *>(VT_EQUIPPED);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyOffset(verifier, VT_NICKNAME) &&
           verifier.VerifyString(nickname()) &&
           VerifyField<ProtoType::Net::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<ProtoType::Net::Rotator>(verifier, VT_LOOK, 4) &&
           VerifyField<float>(verifier, VT_HEALTH, 4) &&
           VerifyField<float>(verifier, VT_MAX_HEALTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_LEVEL, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHARACTER_MODEL_ID, 4) &&
           VerifyOffset(verifier, VT_EQUIPPED) &&
           verifier.VerifyVector(equipped()) &&
           verifier.VerifyVectorOfTables(equipped()) &&
           verifier.EndTable();
  }
  S2C_SendAvatarInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_SendAvatarInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_SendAvatarInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendAvatarInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_SendAvatarInfoBuilder {
  typedef S2C_SendAvatarInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(S2C_SendAvatarInfo::VT_PLAYER_ID, player_id, 0);
  }
  void add_nickname(::flatbuffers::Offset<::flatbuffers::String> nickname) {
    fbb_.AddOffset(S2C_SendAvatarInfo::VT_NICKNAME, nickname);
  }
  void add_position(const ProtoType::Net::Vec3 *position) {
    fbb_.AddStruct(S2C_SendAvatarInfo::VT_POSITION, position);
  }
  void add_look(const ProtoType::Net::Rotator *look) {
    fbb_.AddStruct(S2C_SendAvatarInfo::VT_LOOK, look);
  }
  void add_health(float health) {
    fbb_.AddElement<float>(S2C_SendAvatarInfo::VT_HEALTH, health, 0.0f);
  }
  void add_max_health(float max_health) {
    fbb_.AddElement<float>(S2C_SendAvatarInfo::VT_MAX_HEALTH, max_health, 0.0f);
  }
  void add_level(uint32_t level) {
    fbb_.AddElement<uint32_t>(S2C_SendAvatarInfo::VT_LEVEL, level, 0);
  }
  void add_character_model_id(uint32_t character_model_id) {
    fbb_.AddElement<uint32_t>(S2C_SendAvatarInfo::VT_CHARACTER_MODEL_ID, character_model_id, 0);
  }
  void add_equipped(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>> equipped) {
    fbb_.AddOffset(S2C_SendAvatarInfo::VT_EQUIPPED, equipped);
  }
  explicit S2C_SendAvatarInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_SendAvatarInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_SendAvatarInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_SendAvatarInfo> CreateS2C_SendAvatarInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> nickname = 0,
    const ProtoType::Net::Vec3 *position = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    float health = 0.0f,
    float max_health = 0.0f,
    uint32_t level = 0,
    uint32_t character_model_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>> equipped = 0) {
  S2C_SendAvatarInfoBuilder builder_(_fbb);
  builder_.add_equipped(equipped);
  builder_.add_character_model_id(character_model_id);
  builder_.add_level(level);
  builder_.add_max_health(max_health);
  builder_.add_health(health);
  builder_.add_look(look);
  builder_.add_position(position);
  builder_.add_nickname(nickname);
  builder_.add_player_id(player_id);
  return builder_.Finish();
}

struct S2C_SendAvatarInfo::Traits {
  using type = S2C_SendAvatarInfo;
  static auto constexpr Create = CreateS2C_SendAvatarInfo;
};

inline ::flatbuffers::Offset<S2C_SendAvatarInfo> CreateS2C_SendAvatarInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    const char *nickname = nullptr,
    const ProtoType::Net::Vec3 *position = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    float health = 0.0f,
    float max_health = 0.0f,
    uint32_t level = 0,
    uint32_t character_model_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *equipped = nullptr) {
  auto nickname__ = nickname ? _fbb.CreateString(nickname) : 0;
  auto equipped__ = equipped ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>(*equipped) : 0;
  return ProtoType::Net::CreateS2C_SendAvatarInfo(
      _fbb,
      player_id,
      nickname__,
      position,
      look,
      health,
      max_health,
      level,
      character_model_id,
      equipped__);
}

::flatbuffers::Offset<S2C_SendAvatarInfo> CreateS2C_SendAvatarInfo(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendAvatarInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_SendPlayerInfoT : public ::flatbuffers::NativeTable {
  typedef S2C_SendPlayerInfo TableType;
  uint32_t player_id = 0;
  std::string nickname{};
  std::unique_ptr<ProtoType::Net::Vec3> position{};
  std::unique_ptr<ProtoType::Net::Rotator> look{};
  uint32_t character_model_id = 0;
  std::vector<std::unique_ptr<ProtoType::Net::EquippedVisualT>> equipped{};
  S2C_SendPlayerInfoT() = default;
  S2C_SendPlayerInfoT(const S2C_SendPlayerInfoT &o);
  S2C_SendPlayerInfoT(S2C_SendPlayerInfoT&&) FLATBUFFERS_NOEXCEPT = default;
  S2C_SendPlayerInfoT &operator=(S2C_SendPlayerInfoT o) FLATBUFFERS_NOEXCEPT;
};

struct S2C_SendPlayerInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_SendPlayerInfoT NativeTableType;
  typedef S2C_SendPlayerInfoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_NICKNAME = 6,
    VT_POSITION = 8,
    VT_LOOK = 10,
    VT_CHARACTER_MODEL_ID = 12,
    VT_EQUIPPED = 14
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  const ::flatbuffers::String *nickname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NICKNAME);
  }
  const ProtoType::Net::Vec3 *position() const {
    return GetStruct<const ProtoType::Net::Vec3 *>(VT_POSITION);
  }
  const ProtoType::Net::Rotator *look() const {
    return GetStruct<const ProtoType::Net::Rotator *>(VT_LOOK);
  }
  uint32_t character_model_id() const {
    return GetField<uint32_t>(VT_CHARACTER_MODEL_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *equipped() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *>(VT_EQUIPPED);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyOffset(verifier, VT_NICKNAME) &&
           verifier.VerifyString(nickname()) &&
           VerifyField<ProtoType::Net::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<ProtoType::Net::Rotator>(verifier, VT_LOOK, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHARACTER_MODEL_ID, 4) &&
           VerifyOffset(verifier, VT_EQUIPPED) &&
           verifier.VerifyVector(equipped()) &&
           verifier.VerifyVectorOfTables(equipped()) &&
           verifier.EndTable();
  }
  S2C_SendPlayerInfoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_SendPlayerInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_SendPlayerInfo> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendPlayerInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_SendPlayerInfoBuilder {
  typedef S2C_SendPlayerInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(S2C_SendPlayerInfo::VT_PLAYER_ID, player_id, 0);
  }
  void add_nickname(::flatbuffers::Offset<::flatbuffers::String> nickname) {
    fbb_.AddOffset(S2C_SendPlayerInfo::VT_NICKNAME, nickname);
  }
  void add_position(const ProtoType::Net::Vec3 *position) {
    fbb_.AddStruct(S2C_SendPlayerInfo::VT_POSITION, position);
  }
  void add_look(const ProtoType::Net::Rotator *look) {
    fbb_.AddStruct(S2C_SendPlayerInfo::VT_LOOK, look);
  }
  void add_character_model_id(uint32_t character_model_id) {
    fbb_.AddElement<uint32_t>(S2C_SendPlayerInfo::VT_CHARACTER_MODEL_ID, character_model_id, 0);
  }
  void add_equipped(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>> equipped) {
    fbb_.AddOffset(S2C_SendPlayerInfo::VT_EQUIPPED, equipped);
  }
  explicit S2C_SendPlayerInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_SendPlayerInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_SendPlayerInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_SendPlayerInfo> CreateS2C_SendPlayerInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> nickname = 0,
    const ProtoType::Net::Vec3 *position = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    uint32_t character_model_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>> equipped = 0) {
  S2C_SendPlayerInfoBuilder builder_(_fbb);
  builder_.add_equipped(equipped);
  builder_.add_character_model_id(character_model_id);
  builder_.add_look(look);
  builder_.add_position(position);
  builder_.add_nickname(nickname);
  builder_.add_player_id(player_id);
  return builder_.Finish();
}

struct S2C_SendPlayerInfo::Traits {
  using type = S2C_SendPlayerInfo;
  static auto constexpr Create = CreateS2C_SendPlayerInfo;
};

inline ::flatbuffers::Offset<S2C_SendPlayerInfo> CreateS2C_SendPlayerInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    const char *nickname = nullptr,
    const ProtoType::Net::Vec3 *position = nullptr,
    const ProtoType::Net::Rotator *look = nullptr,
    uint32_t character_model_id = 0,
    const std::vector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> *equipped = nullptr) {
  auto nickname__ = nickname ? _fbb.CreateString(nickname) : 0;
  auto equipped__ = equipped ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>>(*equipped) : 0;
  return ProtoType::Net::CreateS2C_SendPlayerInfo(
      _fbb,
      player_id,
      nickname__,
      position,
      look,
      character_model_id,
      equipped__);
}

::flatbuffers::Offset<S2C_SendPlayerInfo> CreateS2C_SendPlayerInfo(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendPlayerInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline EquippedVisualT *EquippedVisual::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<EquippedVisualT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EquippedVisual::UnPackTo(EquippedVisualT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = slot(); _o->slot = _e; }
  { auto _e = item_id(); _o->item_id = _e; }
}

inline ::flatbuffers::Offset<EquippedVisual> CreateEquippedVisual(::flatbuffers::FlatBufferBuilder &_fbb, const EquippedVisualT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return EquippedVisual::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EquippedVisual> EquippedVisual::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EquippedVisualT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EquippedVisualT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _slot = _o->slot;
  auto _item_id = _o->item_id;
  return ProtoType::Net::CreateEquippedVisual(
      _fbb,
      _slot,
      _item_id);
}

inline S2C_SendAvatarInfoT::S2C_SendAvatarInfoT(const S2C_SendAvatarInfoT &o)
      : player_id(o.player_id),
        nickname(o.nickname),
        position((o.position) ? new ProtoType::Net::Vec3(*o.position) : nullptr),
        look((o.look) ? new ProtoType::Net::Rotator(*o.look) : nullptr),
        health(o.health),
        max_health(o.max_health),
        level(o.level),
        character_model_id(o.character_model_id) {
  equipped.reserve(o.equipped.size());
  for (const auto &equipped_ : o.equipped) { equipped.emplace_back((equipped_) ? new ProtoType::Net::EquippedVisualT(*equipped_) : nullptr); }
}

inline S2C_SendAvatarInfoT &S2C_SendAvatarInfoT::operator=(S2C_SendAvatarInfoT o) FLATBUFFERS_NOEXCEPT {
  std::swap(player_id, o.player_id);
  std::swap(nickname, o.nickname);
  std::swap(position, o.position);
  std::swap(look, o.look);
  std::swap(health, o.health);
  std::swap(max_health, o.max_health);
  std::swap(level, o.level);
  std::swap(character_model_id, o.character_model_id);
  std::swap(equipped, o.equipped);
  return *this;
}

inline S2C_SendAvatarInfoT *S2C_SendAvatarInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_SendAvatarInfoT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_SendAvatarInfo::UnPackTo(S2C_SendAvatarInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = nickname(); if (_e) _o->nickname = _e->str(); }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ProtoType::Net::Vec3>(new ProtoType::Net::Vec3(*_e)); }
  { auto _e = look(); if (_e) _o->look = std::unique_ptr<ProtoType::Net::Rotator>(new ProtoType::Net::Rotator(*_e)); }
  { auto _e = health(); _o->health = _e; }
  { auto _e = max_health(); _o->max_health = _e; }
  { auto _e = level(); _o->level = _e; }
  { auto _e = character_model_id(); _o->character_model_id = _e; }
  { auto _e = equipped(); if (_e) { _o->equipped.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->equipped[_i]) { _e->Get(_i)->UnPackTo(_o->equipped[_i].get(), _resolver); } else { _o->equipped[_i] = std::unique_ptr<ProtoType::Net::EquippedVisualT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->equipped.resize(0); } }
}

inline ::flatbuffers::Offset<S2C_SendAvatarInfo> CreateS2C_SendAvatarInfo(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendAvatarInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_SendAvatarInfo::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_SendAvatarInfo> S2C_SendAvatarInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendAvatarInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_SendAvatarInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _nickname = _o->nickname.empty() ? 0 : _fbb.CreateString(_o->nickname);
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _look = _o->look ? _o->look.get() : nullptr;
  auto _health = _o->health;
  auto _max_health = _o->max_health;
  auto _level = _o->level;
  auto _character_model_id = _o->character_model_id;
  auto _equipped = _o->equipped.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> (_o->equipped.size(), [](size_t i, _VectorArgs *__va) { return CreateEquippedVisual(*__va->__fbb, __va->__o->equipped[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateS2C_SendAvatarInfo(
      _fbb,
      _player_id,
      _nickname,
      _position,
      _look,
      _health,
      _max_health,
      _level,
      _character_model_id,
      _equipped);
}

inline S2C_SendPlayerInfoT::S2C_SendPlayerInfoT(const S2C_SendPlayerInfoT &o)
      : player_id(o.player_id),
        nickname(o.nickname),
        position((o.position) ? new ProtoType::Net::Vec3(*o.position) : nullptr),
        look((o.look) ? new ProtoType::Net::Rotator(*o.look) : nullptr),
        character_model_id(o.character_model_id) {
  equipped.reserve(o.equipped.size());
  for (const auto &equipped_ : o.equipped) { equipped.emplace_back((equipped_) ? new ProtoType::Net::EquippedVisualT(*equipped_) : nullptr); }
}

inline S2C_SendPlayerInfoT &S2C_SendPlayerInfoT::operator=(S2C_SendPlayerInfoT o) FLATBUFFERS_NOEXCEPT {
  std::swap(player_id, o.player_id);
  std::swap(nickname, o.nickname);
  std::swap(position, o.position);
  std::swap(look, o.look);
  std::swap(character_model_id, o.character_model_id);
  std::swap(equipped, o.equipped);
  return *this;
}

inline S2C_SendPlayerInfoT *S2C_SendPlayerInfo::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_SendPlayerInfoT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_SendPlayerInfo::UnPackTo(S2C_SendPlayerInfoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = player_id(); _o->player_id = _e; }
  { auto _e = nickname(); if (_e) _o->nickname = _e->str(); }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ProtoType::Net::Vec3>(new ProtoType::Net::Vec3(*_e)); }
  { auto _e = look(); if (_e) _o->look = std::unique_ptr<ProtoType::Net::Rotator>(new ProtoType::Net::Rotator(*_e)); }
  { auto _e = character_model_id(); _o->character_model_id = _e; }
  { auto _e = equipped(); if (_e) { _o->equipped.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->equipped[_i]) { _e->Get(_i)->UnPackTo(_o->equipped[_i].get(), _resolver); } else { _o->equipped[_i] = std::unique_ptr<ProtoType::Net::EquippedVisualT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->equipped.resize(0); } }
}

inline ::flatbuffers::Offset<S2C_SendPlayerInfo> CreateS2C_SendPlayerInfo(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendPlayerInfoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_SendPlayerInfo::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_SendPlayerInfo> S2C_SendPlayerInfo::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_SendPlayerInfoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_SendPlayerInfoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _player_id = _o->player_id;
  auto _nickname = _o->nickname.empty() ? 0 : _fbb.CreateString(_o->nickname);
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _look = _o->look ? _o->look.get() : nullptr;
  auto _character_model_id = _o->character_model_id;
  auto _equipped = _o->equipped.size() ? _fbb.CreateVector<::flatbuffers::Offset<ProtoType::Net::EquippedVisual>> (_o->equipped.size(), [](size_t i, _VectorArgs *__va) { return CreateEquippedVisual(*__va->__fbb, __va->__o->equipped[i].get(), __va->__rehasher); }, &_va ) : 0;
  return ProtoType::Net::CreateS2C_SendPlayerInfo(
      _fbb,
      _player_id,
      _nickname,
      _position,
      _look,
      _character_model_id,
      _equipped);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_PLAYER_PROTOTYPE_NET_H_
