// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_COMMON_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ProtoType {
namespace Net {

struct Vec2;

struct Vec3;

struct Rotator;

struct Header;

enum class ResultCode : int8_t {
  Ok = 0,
  Failed = 1,
  Denied = 2,
  OutOfRange = 3,
  Busy = 4,
  InvalidTarget = 5,
  Cooldown = 6,
  MIN = Ok,
  MAX = Cooldown
};

inline const ResultCode (&EnumValuesResultCode())[7] {
  static const ResultCode values[] = {
    ResultCode::Ok,
    ResultCode::Failed,
    ResultCode::Denied,
    ResultCode::OutOfRange,
    ResultCode::Busy,
    ResultCode::InvalidTarget,
    ResultCode::Cooldown
  };
  return values;
}

inline const char * const *EnumNamesResultCode() {
  static const char * const names[8] = {
    "Ok",
    "Failed",
    "Denied",
    "OutOfRange",
    "Busy",
    "InvalidTarget",
    "Cooldown",
    nullptr
  };
  return names;
}

inline const char *EnumNameResultCode(ResultCode e) {
  if (::flatbuffers::IsOutRange(e, ResultCode::Ok, ResultCode::Cooldown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResultCode()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  struct Traits;
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

struct Vec2::Traits {
  using type = Vec2;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  struct Traits;
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Vec3::Traits {
  using type = Vec3;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Rotator FLATBUFFERS_FINAL_CLASS {
 private:
  float pitch_;
  float yaw_;
  float roll_;

 public:
  struct Traits;
  Rotator()
      : pitch_(0),
        yaw_(0),
        roll_(0) {
  }
  Rotator(float _pitch, float _yaw, float _roll)
      : pitch_(::flatbuffers::EndianScalar(_pitch)),
        yaw_(::flatbuffers::EndianScalar(_yaw)),
        roll_(::flatbuffers::EndianScalar(_roll)) {
  }
  float pitch() const {
    return ::flatbuffers::EndianScalar(pitch_);
  }
  float yaw() const {
    return ::flatbuffers::EndianScalar(yaw_);
  }
  float roll() const {
    return ::flatbuffers::EndianScalar(roll_);
  }
};
FLATBUFFERS_STRUCT_END(Rotator, 12);

struct Rotator::Traits {
  using type = Rotator;
};

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Header FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t seq_;
  uint32_t client_time_ms_;
  uint32_t player_id_;

 public:
  struct Traits;
  Header()
      : seq_(0),
        client_time_ms_(0),
        player_id_(0) {
  }
  Header(uint32_t _seq, uint32_t _client_time_ms, uint32_t _player_id)
      : seq_(::flatbuffers::EndianScalar(_seq)),
        client_time_ms_(::flatbuffers::EndianScalar(_client_time_ms)),
        player_id_(::flatbuffers::EndianScalar(_player_id)) {
  }
  uint32_t seq() const {
    return ::flatbuffers::EndianScalar(seq_);
  }
  uint32_t client_time_ms() const {
    return ::flatbuffers::EndianScalar(client_time_ms_);
  }
  uint32_t player_id() const {
    return ::flatbuffers::EndianScalar(player_id_);
  }
};
FLATBUFFERS_STRUCT_END(Header, 12);

struct Header::Traits {
  using type = Header;
};

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_COMMON_PROTOTYPE_NET_H_
