// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGIN_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_LOGIN_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ProtoType {
namespace Net {

struct C2S_Login;
struct C2S_LoginBuilder;
struct C2S_LoginT;

struct S2C_LoginFail;
struct S2C_LoginFailBuilder;
struct S2C_LoginFailT;

enum class LoginFailReason : int8_t {
  InvalidToken = 0,
  VersionMismatch = 1,
  ServerFull = 2,
  Banned = 3,
  AlreadyLoggedIn = 4,
  Unknown = 5,
  MIN = InvalidToken,
  MAX = Unknown
};

inline const LoginFailReason (&EnumValuesLoginFailReason())[6] {
  static const LoginFailReason values[] = {
    LoginFailReason::InvalidToken,
    LoginFailReason::VersionMismatch,
    LoginFailReason::ServerFull,
    LoginFailReason::Banned,
    LoginFailReason::AlreadyLoggedIn,
    LoginFailReason::Unknown
  };
  return values;
}

inline const char * const *EnumNamesLoginFailReason() {
  static const char * const names[7] = {
    "InvalidToken",
    "VersionMismatch",
    "ServerFull",
    "Banned",
    "AlreadyLoggedIn",
    "Unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameLoginFailReason(LoginFailReason e) {
  if (::flatbuffers::IsOutRange(e, LoginFailReason::InvalidToken, LoginFailReason::Unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLoginFailReason()[index];
}

struct C2S_LoginT : public ::flatbuffers::NativeTable {
  typedef C2S_Login TableType;
  std::string auth_token{};
  std::string client_version{};
};

struct C2S_Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef C2S_LoginT NativeTableType;
  typedef C2S_LoginBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AUTH_TOKEN = 4,
    VT_CLIENT_VERSION = 6
  };
  const ::flatbuffers::String *auth_token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTH_TOKEN);
  }
  const ::flatbuffers::String *client_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CLIENT_VERSION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_AUTH_TOKEN) &&
           verifier.VerifyString(auth_token()) &&
           VerifyOffset(verifier, VT_CLIENT_VERSION) &&
           verifier.VerifyString(client_version()) &&
           verifier.EndTable();
  }
  C2S_LoginT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(C2S_LoginT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<C2S_Login> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_LoginT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct C2S_LoginBuilder {
  typedef C2S_Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_auth_token(::flatbuffers::Offset<::flatbuffers::String> auth_token) {
    fbb_.AddOffset(C2S_Login::VT_AUTH_TOKEN, auth_token);
  }
  void add_client_version(::flatbuffers::Offset<::flatbuffers::String> client_version) {
    fbb_.AddOffset(C2S_Login::VT_CLIENT_VERSION, client_version);
  }
  explicit C2S_LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<C2S_Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<C2S_Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<C2S_Login> CreateC2S_Login(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> auth_token = 0,
    ::flatbuffers::Offset<::flatbuffers::String> client_version = 0) {
  C2S_LoginBuilder builder_(_fbb);
  builder_.add_client_version(client_version);
  builder_.add_auth_token(auth_token);
  return builder_.Finish();
}

struct C2S_Login::Traits {
  using type = C2S_Login;
  static auto constexpr Create = CreateC2S_Login;
};

inline ::flatbuffers::Offset<C2S_Login> CreateC2S_LoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *auth_token = nullptr,
    const char *client_version = nullptr) {
  auto auth_token__ = auth_token ? _fbb.CreateString(auth_token) : 0;
  auto client_version__ = client_version ? _fbb.CreateString(client_version) : 0;
  return ProtoType::Net::CreateC2S_Login(
      _fbb,
      auth_token__,
      client_version__);
}

::flatbuffers::Offset<C2S_Login> CreateC2S_Login(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_LoginT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S2C_LoginFailT : public ::flatbuffers::NativeTable {
  typedef S2C_LoginFail TableType;
  ProtoType::Net::LoginFailReason reason = ProtoType::Net::LoginFailReason::InvalidToken;
  std::string message{};
};

struct S2C_LoginFail FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S2C_LoginFailT NativeTableType;
  typedef S2C_LoginFailBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REASON = 4,
    VT_MESSAGE = 6
  };
  ProtoType::Net::LoginFailReason reason() const {
    return static_cast<ProtoType::Net::LoginFailReason>(GetField<int8_t>(VT_REASON, 0));
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_REASON, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
  S2C_LoginFailT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S2C_LoginFailT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S2C_LoginFail> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_LoginFailT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S2C_LoginFailBuilder {
  typedef S2C_LoginFail Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reason(ProtoType::Net::LoginFailReason reason) {
    fbb_.AddElement<int8_t>(S2C_LoginFail::VT_REASON, static_cast<int8_t>(reason), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(S2C_LoginFail::VT_MESSAGE, message);
  }
  explicit S2C_LoginFailBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S2C_LoginFail> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S2C_LoginFail>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S2C_LoginFail> CreateS2C_LoginFail(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ProtoType::Net::LoginFailReason reason = ProtoType::Net::LoginFailReason::InvalidToken,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  S2C_LoginFailBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_reason(reason);
  return builder_.Finish();
}

struct S2C_LoginFail::Traits {
  using type = S2C_LoginFail;
  static auto constexpr Create = CreateS2C_LoginFail;
};

inline ::flatbuffers::Offset<S2C_LoginFail> CreateS2C_LoginFailDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ProtoType::Net::LoginFailReason reason = ProtoType::Net::LoginFailReason::InvalidToken,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return ProtoType::Net::CreateS2C_LoginFail(
      _fbb,
      reason,
      message__);
}

::flatbuffers::Offset<S2C_LoginFail> CreateS2C_LoginFail(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_LoginFailT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline C2S_LoginT *C2S_Login::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<C2S_LoginT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void C2S_Login::UnPackTo(C2S_LoginT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = auth_token(); if (_e) _o->auth_token = _e->str(); }
  { auto _e = client_version(); if (_e) _o->client_version = _e->str(); }
}

inline ::flatbuffers::Offset<C2S_Login> CreateC2S_Login(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_LoginT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return C2S_Login::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<C2S_Login> C2S_Login::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const C2S_LoginT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const C2S_LoginT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _auth_token = _o->auth_token.empty() ? 0 : _fbb.CreateString(_o->auth_token);
  auto _client_version = _o->client_version.empty() ? 0 : _fbb.CreateString(_o->client_version);
  return ProtoType::Net::CreateC2S_Login(
      _fbb,
      _auth_token,
      _client_version);
}

inline S2C_LoginFailT *S2C_LoginFail::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S2C_LoginFailT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S2C_LoginFail::UnPackTo(S2C_LoginFailT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = reason(); _o->reason = _e; }
  { auto _e = message(); if (_e) _o->message = _e->str(); }
}

inline ::flatbuffers::Offset<S2C_LoginFail> CreateS2C_LoginFail(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_LoginFailT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return S2C_LoginFail::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S2C_LoginFail> S2C_LoginFail::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S2C_LoginFailT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S2C_LoginFailT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _reason = _o->reason;
  auto _message = _o->message.empty() ? 0 : _fbb.CreateString(_o->message);
  return ProtoType::Net::CreateS2C_LoginFail(
      _fbb,
      _reason,
      _message);
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_LOGIN_PROTOTYPE_NET_H_
