// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKET_PROTOTYPE_NET_H_
#define FLATBUFFERS_GENERATED_PACKET_PROTOTYPE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "attack.h"
#include "interact.h"
#include "item.h"
#include "login.h"
#include "movement.h"
#include "player.h"

namespace ProtoType {
namespace Net {

struct Packet;
struct PacketBuilder;
struct PacketT;

enum class Payload : uint8_t {
  NONE = 0,
  C2S_Login = 1,
  S2C_LoginFail = 2,
  S2C_SendAvatarInfo = 3,
  S2C_SendPlayerInfo = 4,
  C2S_MoveInput = 5,
  S2C_MoveState = 6,
  C2S_AttackRequest = 7,
  S2C_AttackResult = 8,
  C2S_ItemUseRequest = 9,
  S2C_ItemUseResult = 10,
  C2S_InteractRequest = 11,
  S2C_InteractResult = 12,
  MIN = NONE,
  MAX = S2C_InteractResult
};

inline const Payload (&EnumValuesPayload())[13] {
  static const Payload values[] = {
    Payload::NONE,
    Payload::C2S_Login,
    Payload::S2C_LoginFail,
    Payload::S2C_SendAvatarInfo,
    Payload::S2C_SendPlayerInfo,
    Payload::C2S_MoveInput,
    Payload::S2C_MoveState,
    Payload::C2S_AttackRequest,
    Payload::S2C_AttackResult,
    Payload::C2S_ItemUseRequest,
    Payload::S2C_ItemUseResult,
    Payload::C2S_InteractRequest,
    Payload::S2C_InteractResult
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[14] = {
    "NONE",
    "C2S_Login",
    "S2C_LoginFail",
    "S2C_SendAvatarInfo",
    "S2C_SendPlayerInfo",
    "C2S_MoveInput",
    "S2C_MoveState",
    "C2S_AttackRequest",
    "S2C_AttackResult",
    "C2S_ItemUseRequest",
    "S2C_ItemUseResult",
    "C2S_InteractRequest",
    "S2C_InteractResult",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload::NONE, Payload::S2C_InteractResult)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template<typename T> struct PayloadTraits {
  static const Payload enum_value = Payload::NONE;
};

template<> struct PayloadTraits<ProtoType::Net::C2S_Login> {
  static const Payload enum_value = Payload::C2S_Login;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_LoginFail> {
  static const Payload enum_value = Payload::S2C_LoginFail;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_SendAvatarInfo> {
  static const Payload enum_value = Payload::S2C_SendAvatarInfo;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_SendPlayerInfo> {
  static const Payload enum_value = Payload::S2C_SendPlayerInfo;
};

template<> struct PayloadTraits<ProtoType::Net::C2S_MoveInput> {
  static const Payload enum_value = Payload::C2S_MoveInput;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_MoveState> {
  static const Payload enum_value = Payload::S2C_MoveState;
};

template<> struct PayloadTraits<ProtoType::Net::C2S_AttackRequest> {
  static const Payload enum_value = Payload::C2S_AttackRequest;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_AttackResult> {
  static const Payload enum_value = Payload::S2C_AttackResult;
};

template<> struct PayloadTraits<ProtoType::Net::C2S_ItemUseRequest> {
  static const Payload enum_value = Payload::C2S_ItemUseRequest;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_ItemUseResult> {
  static const Payload enum_value = Payload::S2C_ItemUseResult;
};

template<> struct PayloadTraits<ProtoType::Net::C2S_InteractRequest> {
  static const Payload enum_value = Payload::C2S_InteractRequest;
};

template<> struct PayloadTraits<ProtoType::Net::S2C_InteractResult> {
  static const Payload enum_value = Payload::S2C_InteractResult;
};

template<typename T> struct PayloadUnionTraits {
  static const Payload enum_value = Payload::NONE;
};

template<> struct PayloadUnionTraits<ProtoType::Net::C2S_LoginT> {
  static const Payload enum_value = Payload::C2S_Login;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_LoginFailT> {
  static const Payload enum_value = Payload::S2C_LoginFail;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_SendAvatarInfoT> {
  static const Payload enum_value = Payload::S2C_SendAvatarInfo;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_SendPlayerInfoT> {
  static const Payload enum_value = Payload::S2C_SendPlayerInfo;
};

template<> struct PayloadUnionTraits<ProtoType::Net::C2S_MoveInputT> {
  static const Payload enum_value = Payload::C2S_MoveInput;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_MoveStateT> {
  static const Payload enum_value = Payload::S2C_MoveState;
};

template<> struct PayloadUnionTraits<ProtoType::Net::C2S_AttackRequestT> {
  static const Payload enum_value = Payload::C2S_AttackRequest;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_AttackResultT> {
  static const Payload enum_value = Payload::S2C_AttackResult;
};

template<> struct PayloadUnionTraits<ProtoType::Net::C2S_ItemUseRequestT> {
  static const Payload enum_value = Payload::C2S_ItemUseRequest;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_ItemUseResultT> {
  static const Payload enum_value = Payload::S2C_ItemUseResult;
};

template<> struct PayloadUnionTraits<ProtoType::Net::C2S_InteractRequestT> {
  static const Payload enum_value = Payload::C2S_InteractRequest;
};

template<> struct PayloadUnionTraits<ProtoType::Net::S2C_InteractResultT> {
  static const Payload enum_value = Payload::S2C_InteractResult;
};

struct PayloadUnion {
  Payload type;
  void *value;

  PayloadUnion() : type(Payload::NONE), value(nullptr) {}
  PayloadUnion(PayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Payload::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  PayloadUnion(const PayloadUnion &);
  PayloadUnion &operator=(const PayloadUnion &u)
    { PayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  PayloadUnion &operator=(PayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~PayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = PayloadUnionTraits<RT>::enum_value;
    if (type != Payload::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Payload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  ProtoType::Net::C2S_LoginT *AsC2S_Login() {
    return type == Payload::C2S_Login ?
      reinterpret_cast<ProtoType::Net::C2S_LoginT *>(value) : nullptr;
  }
  const ProtoType::Net::C2S_LoginT *AsC2S_Login() const {
    return type == Payload::C2S_Login ?
      reinterpret_cast<const ProtoType::Net::C2S_LoginT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_LoginFailT *AsS2C_LoginFail() {
    return type == Payload::S2C_LoginFail ?
      reinterpret_cast<ProtoType::Net::S2C_LoginFailT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_LoginFailT *AsS2C_LoginFail() const {
    return type == Payload::S2C_LoginFail ?
      reinterpret_cast<const ProtoType::Net::S2C_LoginFailT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_SendAvatarInfoT *AsS2C_SendAvatarInfo() {
    return type == Payload::S2C_SendAvatarInfo ?
      reinterpret_cast<ProtoType::Net::S2C_SendAvatarInfoT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_SendAvatarInfoT *AsS2C_SendAvatarInfo() const {
    return type == Payload::S2C_SendAvatarInfo ?
      reinterpret_cast<const ProtoType::Net::S2C_SendAvatarInfoT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_SendPlayerInfoT *AsS2C_SendPlayerInfo() {
    return type == Payload::S2C_SendPlayerInfo ?
      reinterpret_cast<ProtoType::Net::S2C_SendPlayerInfoT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_SendPlayerInfoT *AsS2C_SendPlayerInfo() const {
    return type == Payload::S2C_SendPlayerInfo ?
      reinterpret_cast<const ProtoType::Net::S2C_SendPlayerInfoT *>(value) : nullptr;
  }
  ProtoType::Net::C2S_MoveInputT *AsC2S_MoveInput() {
    return type == Payload::C2S_MoveInput ?
      reinterpret_cast<ProtoType::Net::C2S_MoveInputT *>(value) : nullptr;
  }
  const ProtoType::Net::C2S_MoveInputT *AsC2S_MoveInput() const {
    return type == Payload::C2S_MoveInput ?
      reinterpret_cast<const ProtoType::Net::C2S_MoveInputT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_MoveStateT *AsS2C_MoveState() {
    return type == Payload::S2C_MoveState ?
      reinterpret_cast<ProtoType::Net::S2C_MoveStateT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_MoveStateT *AsS2C_MoveState() const {
    return type == Payload::S2C_MoveState ?
      reinterpret_cast<const ProtoType::Net::S2C_MoveStateT *>(value) : nullptr;
  }
  ProtoType::Net::C2S_AttackRequestT *AsC2S_AttackRequest() {
    return type == Payload::C2S_AttackRequest ?
      reinterpret_cast<ProtoType::Net::C2S_AttackRequestT *>(value) : nullptr;
  }
  const ProtoType::Net::C2S_AttackRequestT *AsC2S_AttackRequest() const {
    return type == Payload::C2S_AttackRequest ?
      reinterpret_cast<const ProtoType::Net::C2S_AttackRequestT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_AttackResultT *AsS2C_AttackResult() {
    return type == Payload::S2C_AttackResult ?
      reinterpret_cast<ProtoType::Net::S2C_AttackResultT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_AttackResultT *AsS2C_AttackResult() const {
    return type == Payload::S2C_AttackResult ?
      reinterpret_cast<const ProtoType::Net::S2C_AttackResultT *>(value) : nullptr;
  }
  ProtoType::Net::C2S_ItemUseRequestT *AsC2S_ItemUseRequest() {
    return type == Payload::C2S_ItemUseRequest ?
      reinterpret_cast<ProtoType::Net::C2S_ItemUseRequestT *>(value) : nullptr;
  }
  const ProtoType::Net::C2S_ItemUseRequestT *AsC2S_ItemUseRequest() const {
    return type == Payload::C2S_ItemUseRequest ?
      reinterpret_cast<const ProtoType::Net::C2S_ItemUseRequestT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_ItemUseResultT *AsS2C_ItemUseResult() {
    return type == Payload::S2C_ItemUseResult ?
      reinterpret_cast<ProtoType::Net::S2C_ItemUseResultT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_ItemUseResultT *AsS2C_ItemUseResult() const {
    return type == Payload::S2C_ItemUseResult ?
      reinterpret_cast<const ProtoType::Net::S2C_ItemUseResultT *>(value) : nullptr;
  }
  ProtoType::Net::C2S_InteractRequestT *AsC2S_InteractRequest() {
    return type == Payload::C2S_InteractRequest ?
      reinterpret_cast<ProtoType::Net::C2S_InteractRequestT *>(value) : nullptr;
  }
  const ProtoType::Net::C2S_InteractRequestT *AsC2S_InteractRequest() const {
    return type == Payload::C2S_InteractRequest ?
      reinterpret_cast<const ProtoType::Net::C2S_InteractRequestT *>(value) : nullptr;
  }
  ProtoType::Net::S2C_InteractResultT *AsS2C_InteractResult() {
    return type == Payload::S2C_InteractResult ?
      reinterpret_cast<ProtoType::Net::S2C_InteractResultT *>(value) : nullptr;
  }
  const ProtoType::Net::S2C_InteractResultT *AsS2C_InteractResult() const {
    return type == Payload::S2C_InteractResult ?
      reinterpret_cast<const ProtoType::Net::S2C_InteractResultT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type);
template <bool B = false>
bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Payload> *types);

struct PacketT : public ::flatbuffers::NativeTable {
  typedef Packet TableType;
  ProtoType::Net::PayloadUnion payload{};
};

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketT NativeTableType;
  typedef PacketBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  ProtoType::Net::Payload payload_type() const {
    return static_cast<ProtoType::Net::Payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const ProtoType::Net::C2S_Login *payload_as_C2S_Login() const {
    return payload_type() == ProtoType::Net::Payload::C2S_Login ? static_cast<const ProtoType::Net::C2S_Login *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_LoginFail *payload_as_S2C_LoginFail() const {
    return payload_type() == ProtoType::Net::Payload::S2C_LoginFail ? static_cast<const ProtoType::Net::S2C_LoginFail *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_SendAvatarInfo *payload_as_S2C_SendAvatarInfo() const {
    return payload_type() == ProtoType::Net::Payload::S2C_SendAvatarInfo ? static_cast<const ProtoType::Net::S2C_SendAvatarInfo *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_SendPlayerInfo *payload_as_S2C_SendPlayerInfo() const {
    return payload_type() == ProtoType::Net::Payload::S2C_SendPlayerInfo ? static_cast<const ProtoType::Net::S2C_SendPlayerInfo *>(payload()) : nullptr;
  }
  const ProtoType::Net::C2S_MoveInput *payload_as_C2S_MoveInput() const {
    return payload_type() == ProtoType::Net::Payload::C2S_MoveInput ? static_cast<const ProtoType::Net::C2S_MoveInput *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_MoveState *payload_as_S2C_MoveState() const {
    return payload_type() == ProtoType::Net::Payload::S2C_MoveState ? static_cast<const ProtoType::Net::S2C_MoveState *>(payload()) : nullptr;
  }
  const ProtoType::Net::C2S_AttackRequest *payload_as_C2S_AttackRequest() const {
    return payload_type() == ProtoType::Net::Payload::C2S_AttackRequest ? static_cast<const ProtoType::Net::C2S_AttackRequest *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_AttackResult *payload_as_S2C_AttackResult() const {
    return payload_type() == ProtoType::Net::Payload::S2C_AttackResult ? static_cast<const ProtoType::Net::S2C_AttackResult *>(payload()) : nullptr;
  }
  const ProtoType::Net::C2S_ItemUseRequest *payload_as_C2S_ItemUseRequest() const {
    return payload_type() == ProtoType::Net::Payload::C2S_ItemUseRequest ? static_cast<const ProtoType::Net::C2S_ItemUseRequest *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_ItemUseResult *payload_as_S2C_ItemUseResult() const {
    return payload_type() == ProtoType::Net::Payload::S2C_ItemUseResult ? static_cast<const ProtoType::Net::S2C_ItemUseResult *>(payload()) : nullptr;
  }
  const ProtoType::Net::C2S_InteractRequest *payload_as_C2S_InteractRequest() const {
    return payload_type() == ProtoType::Net::Payload::C2S_InteractRequest ? static_cast<const ProtoType::Net::C2S_InteractRequest *>(payload()) : nullptr;
  }
  const ProtoType::Net::S2C_InteractResult *payload_as_S2C_InteractResult() const {
    return payload_type() == ProtoType::Net::Payload::S2C_InteractResult ? static_cast<const ProtoType::Net::S2C_InteractResult *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  PacketT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PacketT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Packet> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const ProtoType::Net::C2S_Login *Packet::payload_as<ProtoType::Net::C2S_Login>() const {
  return payload_as_C2S_Login();
}

template<> inline const ProtoType::Net::S2C_LoginFail *Packet::payload_as<ProtoType::Net::S2C_LoginFail>() const {
  return payload_as_S2C_LoginFail();
}

template<> inline const ProtoType::Net::S2C_SendAvatarInfo *Packet::payload_as<ProtoType::Net::S2C_SendAvatarInfo>() const {
  return payload_as_S2C_SendAvatarInfo();
}

template<> inline const ProtoType::Net::S2C_SendPlayerInfo *Packet::payload_as<ProtoType::Net::S2C_SendPlayerInfo>() const {
  return payload_as_S2C_SendPlayerInfo();
}

template<> inline const ProtoType::Net::C2S_MoveInput *Packet::payload_as<ProtoType::Net::C2S_MoveInput>() const {
  return payload_as_C2S_MoveInput();
}

template<> inline const ProtoType::Net::S2C_MoveState *Packet::payload_as<ProtoType::Net::S2C_MoveState>() const {
  return payload_as_S2C_MoveState();
}

template<> inline const ProtoType::Net::C2S_AttackRequest *Packet::payload_as<ProtoType::Net::C2S_AttackRequest>() const {
  return payload_as_C2S_AttackRequest();
}

template<> inline const ProtoType::Net::S2C_AttackResult *Packet::payload_as<ProtoType::Net::S2C_AttackResult>() const {
  return payload_as_S2C_AttackResult();
}

template<> inline const ProtoType::Net::C2S_ItemUseRequest *Packet::payload_as<ProtoType::Net::C2S_ItemUseRequest>() const {
  return payload_as_C2S_ItemUseRequest();
}

template<> inline const ProtoType::Net::S2C_ItemUseResult *Packet::payload_as<ProtoType::Net::S2C_ItemUseResult>() const {
  return payload_as_S2C_ItemUseResult();
}

template<> inline const ProtoType::Net::C2S_InteractRequest *Packet::payload_as<ProtoType::Net::C2S_InteractRequest>() const {
  return payload_as_C2S_InteractRequest();
}

template<> inline const ProtoType::Net::S2C_InteractResult *Packet::payload_as<ProtoType::Net::S2C_InteractResult>() const {
  return payload_as_S2C_InteractResult();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(ProtoType::Net::Payload payload_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(Packet::VT_PAYLOAD, payload);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ProtoType::Net::Payload payload_type = ProtoType::Net::Payload::NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct Packet::Traits {
  using type = Packet;
  static auto constexpr Create = CreatePacket;
};

::flatbuffers::Offset<Packet> CreatePacket(::flatbuffers::FlatBufferBuilder &_fbb, const PacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline PacketT *Packet::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PacketT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Packet::UnPackTo(PacketT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = ProtoType::Net::PayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<Packet> CreatePacket(::flatbuffers::FlatBufferBuilder &_fbb, const PacketT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Packet::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Packet> Packet::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PacketT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PacketT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return ProtoType::Net::CreatePacket(
      _fbb,
      _payload_type,
      _payload);
}

template <bool B>
inline bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload::NONE: {
      return true;
    }
    case Payload::C2S_Login: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_Login *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_LoginFail: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_LoginFail *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_SendAvatarInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendAvatarInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_SendPlayerInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendPlayerInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::C2S_MoveInput: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_MoveInput *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_MoveState: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_MoveState *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::C2S_AttackRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_AttackRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_AttackResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_AttackResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::C2S_ItemUseRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_ItemUseRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_ItemUseResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_ItemUseResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::C2S_InteractRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_InteractRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload::S2C_InteractResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_InteractResult *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Payload> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *PayloadUnion::UnPack(const void *obj, Payload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Payload::C2S_Login: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_Login *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_LoginFail: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_LoginFail *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_SendAvatarInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendAvatarInfo *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_SendPlayerInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendPlayerInfo *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::C2S_MoveInput: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_MoveInput *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_MoveState: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_MoveState *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::C2S_AttackRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_AttackRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_AttackResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_AttackResult *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::C2S_ItemUseRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_ItemUseRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_ItemUseResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_ItemUseResult *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::C2S_InteractRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_InteractRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload::S2C_InteractResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_InteractResult *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> PayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Payload::C2S_Login: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_LoginT *>(value);
      return CreateC2S_Login(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_LoginFail: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_LoginFailT *>(value);
      return CreateS2C_LoginFail(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_SendAvatarInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendAvatarInfoT *>(value);
      return CreateS2C_SendAvatarInfo(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_SendPlayerInfo: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_SendPlayerInfoT *>(value);
      return CreateS2C_SendPlayerInfo(_fbb, ptr, _rehasher).Union();
    }
    case Payload::C2S_MoveInput: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_MoveInputT *>(value);
      return CreateC2S_MoveInput(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_MoveState: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_MoveStateT *>(value);
      return CreateS2C_MoveState(_fbb, ptr, _rehasher).Union();
    }
    case Payload::C2S_AttackRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_AttackRequestT *>(value);
      return CreateC2S_AttackRequest(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_AttackResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_AttackResultT *>(value);
      return CreateS2C_AttackResult(_fbb, ptr, _rehasher).Union();
    }
    case Payload::C2S_ItemUseRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_ItemUseRequestT *>(value);
      return CreateC2S_ItemUseRequest(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_ItemUseResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_ItemUseResultT *>(value);
      return CreateS2C_ItemUseResult(_fbb, ptr, _rehasher).Union();
    }
    case Payload::C2S_InteractRequest: {
      auto ptr = reinterpret_cast<const ProtoType::Net::C2S_InteractRequestT *>(value);
      return CreateC2S_InteractRequest(_fbb, ptr, _rehasher).Union();
    }
    case Payload::S2C_InteractResult: {
      auto ptr = reinterpret_cast<const ProtoType::Net::S2C_InteractResultT *>(value);
      return CreateS2C_InteractResult(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline PayloadUnion::PayloadUnion(const PayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Payload::C2S_Login: {
      value = new ProtoType::Net::C2S_LoginT(*reinterpret_cast<ProtoType::Net::C2S_LoginT *>(u.value));
      break;
    }
    case Payload::S2C_LoginFail: {
      value = new ProtoType::Net::S2C_LoginFailT(*reinterpret_cast<ProtoType::Net::S2C_LoginFailT *>(u.value));
      break;
    }
    case Payload::S2C_SendAvatarInfo: {
      value = new ProtoType::Net::S2C_SendAvatarInfoT(*reinterpret_cast<ProtoType::Net::S2C_SendAvatarInfoT *>(u.value));
      break;
    }
    case Payload::S2C_SendPlayerInfo: {
      value = new ProtoType::Net::S2C_SendPlayerInfoT(*reinterpret_cast<ProtoType::Net::S2C_SendPlayerInfoT *>(u.value));
      break;
    }
    case Payload::C2S_MoveInput: {
      value = new ProtoType::Net::C2S_MoveInputT(*reinterpret_cast<ProtoType::Net::C2S_MoveInputT *>(u.value));
      break;
    }
    case Payload::S2C_MoveState: {
      value = new ProtoType::Net::S2C_MoveStateT(*reinterpret_cast<ProtoType::Net::S2C_MoveStateT *>(u.value));
      break;
    }
    case Payload::C2S_AttackRequest: {
      value = new ProtoType::Net::C2S_AttackRequestT(*reinterpret_cast<ProtoType::Net::C2S_AttackRequestT *>(u.value));
      break;
    }
    case Payload::S2C_AttackResult: {
      value = new ProtoType::Net::S2C_AttackResultT(*reinterpret_cast<ProtoType::Net::S2C_AttackResultT *>(u.value));
      break;
    }
    case Payload::C2S_ItemUseRequest: {
      value = new ProtoType::Net::C2S_ItemUseRequestT(*reinterpret_cast<ProtoType::Net::C2S_ItemUseRequestT *>(u.value));
      break;
    }
    case Payload::S2C_ItemUseResult: {
      value = new ProtoType::Net::S2C_ItemUseResultT(*reinterpret_cast<ProtoType::Net::S2C_ItemUseResultT *>(u.value));
      break;
    }
    case Payload::C2S_InteractRequest: {
      value = new ProtoType::Net::C2S_InteractRequestT(*reinterpret_cast<ProtoType::Net::C2S_InteractRequestT *>(u.value));
      break;
    }
    case Payload::S2C_InteractResult: {
      value = new ProtoType::Net::S2C_InteractResultT(*reinterpret_cast<ProtoType::Net::S2C_InteractResultT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void PayloadUnion::Reset() {
  switch (type) {
    case Payload::C2S_Login: {
      auto ptr = reinterpret_cast<ProtoType::Net::C2S_LoginT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_LoginFail: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_LoginFailT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_SendAvatarInfo: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_SendAvatarInfoT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_SendPlayerInfo: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_SendPlayerInfoT *>(value);
      delete ptr;
      break;
    }
    case Payload::C2S_MoveInput: {
      auto ptr = reinterpret_cast<ProtoType::Net::C2S_MoveInputT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_MoveState: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_MoveStateT *>(value);
      delete ptr;
      break;
    }
    case Payload::C2S_AttackRequest: {
      auto ptr = reinterpret_cast<ProtoType::Net::C2S_AttackRequestT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_AttackResult: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_AttackResultT *>(value);
      delete ptr;
      break;
    }
    case Payload::C2S_ItemUseRequest: {
      auto ptr = reinterpret_cast<ProtoType::Net::C2S_ItemUseRequestT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_ItemUseResult: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_ItemUseResultT *>(value);
      delete ptr;
      break;
    }
    case Payload::C2S_InteractRequest: {
      auto ptr = reinterpret_cast<ProtoType::Net::C2S_InteractRequestT *>(value);
      delete ptr;
      break;
    }
    case Payload::S2C_InteractResult: {
      auto ptr = reinterpret_cast<ProtoType::Net::S2C_InteractResultT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Payload::NONE;
}

inline const ProtoType::Net::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<ProtoType::Net::Packet>(buf);
}

inline const ProtoType::Net::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ProtoType::Net::Packet>(buf);
}

inline const char *PacketIdentifier() {
  return "PTPK";
}

inline bool PacketBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PacketIdentifier());
}

inline bool SizePrefixedPacketBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, PacketIdentifier(), true);
}

template <bool B = false>
inline bool VerifyPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ProtoType::Net::Packet>(PacketIdentifier());
}

template <bool B = false>
inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ProtoType::Net::Packet>(PacketIdentifier());
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ProtoType::Net::Packet> root) {
  fbb.Finish(root, PacketIdentifier());
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ProtoType::Net::Packet> root) {
  fbb.FinishSizePrefixed(root, PacketIdentifier());
}

inline std::unique_ptr<ProtoType::Net::PacketT> UnPackPacket(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<ProtoType::Net::PacketT>(GetPacket(buf)->UnPack(res));
}

inline std::unique_ptr<ProtoType::Net::PacketT> UnPackSizePrefixedPacket(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<ProtoType::Net::PacketT>(GetSizePrefixedPacket(buf)->UnPack(res));
}

}  // namespace Net
}  // namespace ProtoType

#endif  // FLATBUFFERS_GENERATED_PACKET_PROTOTYPE_NET_H_
